// Code generated by scripts/generate-sdk-types.ts. DO NOT EDIT.
//
// Source: npm run sdk:generate-types
// Generated from OpenAPI spec via src/openapi/registry.ts

package proof

// ============================================================================
// Common
// ============================================================================

type APIInfo struct {
	Name string `json:"name"`
	Version string `json:"version"`
	Description string `json:"description"`
	Links map[string]any `json:"links"`
}

// ErrorDetail Field-level validation error detail
type ErrorDetail struct {
	Field string `json:"field"`
	Message string `json:"message"`
	Code string `json:"code"`
}

// ErrorResponse Standard error response format
type ErrorResponse struct {
	Error map[string]any `json:"error"`
}

// HealthResponse Detailed health check response
type HealthResponse struct {
	Status string `json:"status"`
	Timestamp any `json:"timestamp"`
}

// LivenessResponse Liveness probe response — always returns ok if the process is alive
type LivenessResponse struct {
	Status string `json:"status"`
	Timestamp string `json:"timestamp"`
}

type ObjectId = string

type IdParam struct {
	ID ObjectId `json:"id"`
}

// PaginationResponse Pagination info in list responses
type PaginationResponse struct {
	Page *int `json:"page,omitempty"`
	Limit *int `json:"limit,omitempty"`
	Total *int `json:"total,omitempty"`
	Pages *int `json:"pages,omitempty"`
	HasMore *bool `json:"hasMore,omitempty"`
	NextCursor *string `json:"nextCursor,omitempty"`
}

// RevocationReason represents the possible values for revocation reason.
type RevocationReason = string

// SuccessResponse Generic success response
type SuccessResponse struct {
	Success bool `json:"success"`
	Message *string `json:"message,omitempty"`
}

// ============================================================================
// Verification Requests
// ============================================================================

// ActionContext Context for custom and confirmation action types
type ActionContext struct {
	Title *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Amount *float64 `json:"amount,omitempty"`
	Currency *string `json:"currency,omitempty"`
	Entity *string `json:"entity,omitempty"`
}

// ActionType represents the possible values for action type.
type ActionType = string

type CancelRequestResponse struct {
	Success bool `json:"success"`
	Status string `json:"status"`
}

type ReferenceIdParam struct {
	ReferenceID string `json:"referenceId"`
}

// RequestedAsset Asset to be verified in a multi-asset request
type RequestedAsset struct {
	Type VerificationType `json:"type"`
	Identifier *string `json:"identifier,omitempty"`
	Channel any `json:"channel,omitempty"`
	AllowedChannels []VerificationChannel `json:"allowed_channels,omitempty"`
	Required *bool `json:"required,omitempty"`
}

// ============================================================================
// Domains
// ============================================================================

// AddDomainRequest Request body for adding a domain
type AddDomainRequest struct {
	Domain string `json:"domain"`
	ProjectID *string `json:"project_id,omitempty"`
	ForEmailSending *bool `json:"for_email_sending,omitempty"`
	VerificationMethod *string `json:"verification_method,omitempty"`
}

// ConnectCloudflareRequest Request body for connecting a Cloudflare API token
type ConnectCloudflareRequest struct {
	APIToken string `json:"api_token"`
}

// ConnectGoDaddyRequest Request body for connecting GoDaddy API credentials
type ConnectGoDaddyRequest struct {
	APIKey string `json:"api_key"`
	APISecret string `json:"api_secret"`
}

// ConnectProviderRequest Request body for connecting a generic DNS provider
type ConnectProviderRequest struct {
	Credentials map[string]any `json:"credentials"`
}

// DomainStatus represents the possible values for domain status.
type DomainStatus = string

// Domain Domain record
type Domain struct {
	ID ObjectId `json:"id"`
	Domain string `json:"domain"`
	Status DomainStatus `json:"status"`
	VerificationMethod *string `json:"verification_method,omitempty"`
	Provider *string `json:"provider,omitempty"`
	EmailSendingEnabled *bool `json:"email_sending_enabled,omitempty"`
	ProjectID *ObjectId `json:"project_id,omitempty"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	VerifiedAt *string `json:"verified_at,omitempty"`
}

// DomainCheckResponse Domain verification check result
type DomainCheckResponse struct {
	ID ObjectId `json:"id"`
	Domain string `json:"domain"`
	Status string `json:"status"`
	Verified bool `json:"verified"`
	VerifiedAt *string `json:"verified_at"`
	CheckCount int `json:"check_count"`
}

// DomainVerificationResponse Domain verification initiation response
type DomainVerificationResponse struct {
	ID ObjectId `json:"id"`
	Domain string `json:"domain"`
	Status string `json:"status"`
	VerificationMethod string `json:"verification_method"`
	DNSRecord map[string]any `json:"dns_record"`
	HTTPFile map[string]any `json:"http_file"`
	Provider map[string]any `json:"provider"`
}

type ProviderParam struct {
	ID ObjectId `json:"id"`
	Provider string `json:"provider"`
}

// SetupEmailSendingRequest Request body for setting up email sending on a domain
type SetupEmailSendingRequest struct {
	FromEmail *string `json:"from_email,omitempty"`
}

// StartDomainVerificationRequest Request body for starting B2B domain verification
type StartDomainVerificationRequest struct {
	Domain string `json:"domain"`
	CustomerID *string `json:"customer_id,omitempty"`
	VerificationMethod *string `json:"verification_method,omitempty"`
}

// StartEmailVerificationRequest Request body for starting email-based domain verification
type StartEmailVerificationRequest struct {
	EmailPrefix *string `json:"email_prefix,omitempty"`
}

// StartUserDomainVerificationRequest Request body for starting user domain verification
type StartUserDomainVerificationRequest struct {
	Domain string `json:"domain"`
	Channel *string `json:"channel,omitempty"`
}

// ============================================================================
// Emails
// ============================================================================

// AddEmailRequest Request body for adding a new email
type AddEmailRequest struct {
	Email string `json:"email"`
}

// UserEmail User email address
type UserEmail struct {
	ID ObjectId `json:"id"`
	Email string `json:"email"`
	IsPrimary bool `json:"is_primary"`
	VerifiedAt *string `json:"verified_at,omitempty"`
	CreatedAt string `json:"created_at"`
}

// VerifyCodeRequest OTP code submission
type VerifyCodeRequest struct {
	Code string `json:"code"`
}

// ============================================================================
// Phones
// ============================================================================

// AddPhoneRequest Request body for adding a new phone
type AddPhoneRequest struct {
	Channel string `json:"channel"`
}

// UserPhone User phone number
type UserPhone struct {
	ID ObjectId `json:"id"`
	Phone string `json:"phone"`
	IsPrimary bool `json:"is_primary"`
	VerifiedAt *string `json:"verified_at,omitempty"`
	CreatedAt string `json:"created_at"`
	ChannelMetadata map[string]any `json:"channel_metadata,omitempty"`
}

// ============================================================================
// Assets
// ============================================================================

// AssetStatus represents the possible values for asset status.
type AssetStatus = string

// ListAssetsQuery Query parameters for listing assets
type ListAssetsQuery struct {
	Type *string `json:"type,omitempty"`
	Status *AssetStatus `json:"status,omitempty"`
}

type AssetIndexParam struct {
	ID ObjectId `json:"id"`
	AssetIndex string `json:"assetIndex"`
}

// UserAsset User verified asset
type UserAsset struct {
	ID ObjectId `json:"id"`
	Type VerificationType `json:"type"`
	Channel VerificationChannel `json:"channel"`
	Identifier string `json:"identifier"`
	Status AssetStatus `json:"status"`
	VerifiedAt *string `json:"verified_at,omitempty"`
	ExpiresAt *string `json:"expires_at,omitempty"`
	CreatedAt string `json:"created_at"`
}

// ============================================================================
// Auth
// ============================================================================

// AuthChannel represents the possible values for auth channel.
type AuthChannel = string

type AuthSessionIdParam struct {
	SessionID string `json:"sessionId"`
}

// AuthSessionListItem Active session entry
type AuthSessionListItem struct {
	ID string `json:"id"`
	Channel AuthChannel `json:"channel"`
	UserAgent *string `json:"user_agent,omitempty"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
	IsCurrent bool `json:"is_current"`
}

// AuthSessionStatus represents the possible values for auth session status.
type AuthSessionStatus = string

// AuthSessionResponse Auth session response
type AuthSessionResponse struct {
	ID string `json:"id"`
	Type string `json:"type"`
	Channel AuthChannel `json:"channel"`
	Status AuthSessionStatus `json:"status"`
	DeepLink *string `json:"deep_link,omitempty"`
	QRCode *string `json:"qr_code,omitempty"`
	ExpiresAt string `json:"expires_at"`
	Instructions *string `json:"instructions,omitempty"`
	VerifiedAt *string `json:"verified_at,omitempty"`
	UserID *string `json:"user_id,omitempty"`
}

// CreateAuthSessionRequest Request body for creating a new auth session (login)
type CreateAuthSessionRequest struct {
	Channel AuthChannel `json:"channel"`
	PhoneNumber *string `json:"phone_number,omitempty"`
	Email *string `json:"email,omitempty"`
}

// ExchangeTokenRequest Request body for exchanging a one-time token for JWT
type ExchangeTokenRequest struct {
	Token string `json:"token"`
}

// ExchangeTokenResponse Token exchange response
type ExchangeTokenResponse struct {
	Success bool `json:"success"`
	JWT string `json:"jwt"`
	ExpiresAt string `json:"expiresAt"`
}

// ListSessionsResponse List of active sessions
type ListSessionsResponse struct {
	Sessions []AuthSessionListItem `json:"sessions"`
	Total int `json:"total"`
}

// LogoutAllResponse Logout all devices response
type LogoutAllResponse struct {
	Success bool `json:"success"`
	Message string `json:"message"`
	Invalidated int `json:"invalidated"`
}

// AuthUser Authenticated user profile
type AuthUser struct {
	ID ObjectId `json:"id"`
	PhoneNumbers []map[string]any `json:"phone_numbers,omitempty"`
	Emails []map[string]any `json:"emails,omitempty"`
	CreatedAt string `json:"created_at"`
}

// SubmitAuthCodeRequest Request body for submitting an auth OTP code
type SubmitAuthCodeRequest struct {
	Code string `json:"code"`
}

type TokenParam struct {
	Token string `json:"token"`
}

// TransferTokenResponse Transfer token generation response
type TransferTokenResponse struct {
	Success bool `json:"success"`
	Token string `json:"token"`
	URL string `json:"url"`
	ExpiresIn int `json:"expiresIn"`
}

// ============================================================================
// Authorizations
// ============================================================================

// AuthorizationChannel represents the possible values for authorization channel.
type AuthorizationChannel = string

// AuthorizationScope represents the possible values for authorization scope.
type AuthorizationScope = string

// AuthorizationStatus represents the possible values for authorization status.
type AuthorizationStatus = string

type AuthorizationExportQuery struct {
	Format *string `json:"format,omitempty"`
	From *string `json:"from,omitempty"`
	To *string `json:"to,omitempty"`
	Status *AuthorizationStatus `json:"status,omitempty"`
}

type AuthorizationListQuery struct {
	Page *int `json:"page,omitempty"`
	Limit *int `json:"limit,omitempty"`
	Status *AuthorizationStatus `json:"status,omitempty"`
	Phone *string `json:"phone,omitempty"`
	Channel *AuthorizationChannel `json:"channel,omitempty"`
}

// Authorization Authorization granting permission to send confirmations via a specific channel
type Authorization struct {
	ID ObjectId `json:"id"`
	Status AuthorizationStatus `json:"status"`
	HitlID any `json:"hitl_id"`
	Recipient *string `json:"recipient,omitempty"`
	Phone *string `json:"phone,omitempty"`
	Channel AuthorizationChannel `json:"channel"`
	Scope AuthorizationScope `json:"scope"`
	BusinessName string `json:"business_name"`
	VerificationID *ObjectId `json:"verification_id,omitempty"`
	AuthorizedAt *string `json:"authorized_at,omitempty"`
	ExpiresAt string `json:"expires_at"`
	RevokedAt *string `json:"revoked_at,omitempty"`
	RevocationReason *string `json:"revocation_reason,omitempty"`
	ConfirmationsSent int `json:"confirmations_sent"`
	LastUsedAt *string `json:"last_used_at,omitempty"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type AuthorizationListResponse struct {
	Data []Authorization `json:"data"`
	Pagination map[string]any `json:"pagination"`
}

// CreateAuthorizationBody Request body for creating an authorization
type CreateAuthorizationBody struct {
	HitlID any `json:"hitl_id"`
	Recipient string `json:"recipient"`
	Phone string `json:"phone"`
	Channel AuthorizationChannel `json:"channel"`
	Scope any `json:"scope,omitempty"`
	BusinessName string `json:"business_name"`
	BusinessProfileID any `json:"business_profile_id,omitempty"`
	ExpiresIn *int `json:"expires_in,omitempty"`
}

// CreateAuthorizationResponse Response from creating an authorization request
type CreateAuthorizationResponse struct {
	ID ObjectId `json:"id"`
	Status AuthorizationStatus `json:"status"`
	HitlID any `json:"hitl_id"`
	Recipient *string `json:"recipient,omitempty"`
	Phone *string `json:"phone,omitempty"`
	Channel AuthorizationChannel `json:"channel"`
	Scope AuthorizationScope `json:"scope"`
	BusinessName string `json:"business_name"`
	AuthorizationURL string `json:"authorization_url"`
	ExpiresAt string `json:"expires_at"`
	CreatedAt string `json:"created_at"`
}

type RevokeAuthorizationBody struct {
	Reason *string `json:"reason,omitempty"`
}

// ============================================================================
// Billing
// ============================================================================

// BillingPlan represents the possible values for billing plan.
type BillingPlan = string

// CheckoutRequest Request body for creating a Stripe checkout session
type CheckoutRequest struct {
	Plan BillingPlan `json:"plan"`
	SuccessURL string `json:"success_url"`
	CancelURL string `json:"cancel_url"`
}

// CheckoutResponse Checkout session creation response
type CheckoutResponse struct {
	URL string `json:"url"`
}

// PortalRequest Request body for creating a Stripe billing portal session
type PortalRequest struct {
	ReturnURL string `json:"return_url"`
}

// PortalResponse Billing portal session creation response
type PortalResponse struct {
	URL string `json:"url"`
}

// ============================================================================
// Settings
// ============================================================================

// BrandingSettings Branding settings
type BrandingSettings struct {
	BusinessName *string `json:"business_name,omitempty"`
	LogoURL *string `json:"logo_url,omitempty"`
	PrimaryColor *string `json:"primary_color,omitempty"`
	SupportEmail *string `json:"support_email,omitempty"`
	EmailTheme *string `json:"email_theme,omitempty"`
}

// UpdateSettingsRequest Request body for updating user settings
type UpdateSettingsRequest struct {
	Branding *BrandingSettings `json:"branding,omitempty"`
}

// UsageQueryParams Usage query parameters
type UsageQueryParams struct {
	Period *string `json:"period,omitempty"`
	Months *int `json:"months,omitempty"`
}

// ============================================================================
// Verifications
// ============================================================================

// Challenge Challenge details for verification
type Challenge struct {
	Code *string `json:"code,omitempty"`
	Instruction *string `json:"instruction,omitempty"`
	ExpiresAt *string `json:"expires_at,omitempty"`
}

// DNSProviderCredentials DNS provider credentials for auto-DNS verification
type DNSProviderCredentials struct {
	Provider string `json:"provider"`
	APIToken *string `json:"api_token,omitempty"`
	APIKey *string `json:"api_key,omitempty"`
	APISecret *string `json:"api_secret,omitempty"`
	AccountID *string `json:"account_id,omitempty"`
	Username *string `json:"username,omitempty"`
	AccessKeyID *string `json:"access_key_id,omitempty"`
	SecretAccessKey *string `json:"secret_access_key,omitempty"`
	Region *string `json:"region,omitempty"`
}

// ResendVerificationResponse Response after resending verification email
type ResendVerificationResponse struct {
	Success bool `json:"success"`
	Message string `json:"message"`
	ExpiresAt string `json:"expires_at"`
}

// SubmitChallengeRequest Request body for submitting a challenge code
type SubmitChallengeRequest struct {
	ChallengeCode string `json:"challenge_code"`
	SourceIdentifier *string `json:"source_identifier,omitempty"`
}

// SubmitVerificationCodeRequest Request body for submitting a verification code
type SubmitVerificationCodeRequest struct {
	Code string `json:"code"`
}

// VerificationChannel represents the possible values for verification channel.
type VerificationChannel = string

// VerificationRequestStatus represents the possible values for verification request status.
type VerificationRequestStatus = string

type VerificationRequestListQuery struct {
	Page *int `json:"page,omitempty"`
	Limit *int `json:"limit,omitempty"`
	Status *VerificationRequestStatus `json:"status,omitempty"`
	ReferenceID *string `json:"reference_id,omitempty"`
}

// VerificationStatus represents the possible values for verification status.
type VerificationStatus = string

// VerificationType represents the possible values for verification type.
type VerificationType = string

// CreateVerificationRequest Request body for creating a new verification
type CreateVerificationRequest struct {
	Type VerificationType `json:"type"`
	Channel VerificationChannel `json:"channel"`
	Identifier string `json:"identifier"`
	ExternalUserID *string `json:"external_user_id,omitempty"`
	ClientMetadata map[string]any `json:"client_metadata,omitempty"`
	DNSProvider any `json:"dns_provider,omitempty"`
	EmailPrefix *string `json:"email_prefix,omitempty"`
	BotToken *string `json:"bot_token,omitempty"`
	ProofExpiryDays *int `json:"proof_expiry_days,omitempty"`
}

// CreateVerificationRequestBody Request body for creating a multi-asset verification request
type CreateVerificationRequestBody struct {
	ReferenceID *string `json:"reference_id,omitempty"`
	ProjectID any `json:"project_id,omitempty"`
	PublicProfileID any `json:"public_profile_id,omitempty"`
	Assets []RequestedAsset `json:"assets"`
	ActionType any `json:"action_type,omitempty"`
	ActionContext *ActionContext `json:"action_context,omitempty"`
	ValidityRequirement *string `json:"validity_requirement,omitempty"`
	PartialOk *bool `json:"partial_ok,omitempty"`
	RedirectURL *string `json:"redirect_url,omitempty"`
	CallbackURL *string `json:"callback_url,omitempty"`
	ExpiresIn *int `json:"expires_in,omitempty"`
	ProofExpiryDays *int `json:"proof_expiry_days,omitempty"`
}

type TestVerifyResponse struct {
	ID ObjectId `json:"id"`
	Type VerificationType `json:"type"`
	Channel string `json:"channel"`
	Status string `json:"status"`
	Identifier string `json:"identifier"`
	VerifiedAt string `json:"verified_at"`
	ProofToken string `json:"proof_token"`
	ProofExpiresAt string `json:"proof_expires_at"`
	TestMode bool `json:"test_mode"`
}

// Verification Verification object
type Verification struct {
	ID ObjectId `json:"id"`
	Type VerificationType `json:"type"`
	Channel VerificationChannel `json:"channel"`
	Identifier string `json:"identifier"`
	Status VerificationStatus `json:"status"`
	Challenge *Challenge `json:"challenge,omitempty"`
	Proof *Proof `json:"proof,omitempty"`
	ExternalUserID *string `json:"external_user_id,omitempty"`
	Attempts *int `json:"attempts,omitempty"`
	MaxAttempts *int `json:"max_attempts,omitempty"`
	CreatedAt string `json:"created_at"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	VerifiedAt *string `json:"verified_at,omitempty"`
}

type VerificationListQuery struct {
	Page *int `json:"page,omitempty"`
	Limit *int `json:"limit,omitempty"`
	Status *VerificationStatus `json:"status,omitempty"`
	Type *VerificationType `json:"type,omitempty"`
}

// VerificationListResponse Paginated list of verifications
type VerificationListResponse struct {
	Data []Verification `json:"data"`
	Pagination PaginationResponse `json:"pagination"`
}

// VerificationRequest Multi-asset verification request
type VerificationRequest struct {
	ID ObjectId `json:"id"`
	ReferenceID *string `json:"reference_id,omitempty"`
	Status VerificationRequestStatus `json:"status"`
	Assets []map[string]any `json:"assets"`
	ActionType ActionType `json:"action_type"`
	ActionContext *ActionContext `json:"action_context,omitempty"`
	PartialOk bool `json:"partial_ok"`
	VerificationURL *string `json:"verification_url,omitempty"`
	RedirectURL *string `json:"redirect_url,omitempty"`
	Progress map[string]any `json:"progress,omitempty"`
	ExpiresAt string `json:"expires_at"`
	CompletedAt *string `json:"completed_at,omitempty"`
	CreatedAt string `json:"created_at"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

type VerificationRequestListResponse struct {
	Data []VerificationRequest `json:"data"`
	Pagination map[string]any `json:"pagination"`
}

// VerificationRequestProofsResponse Proof tokens for verified assets in a verification request
type VerificationRequestProofsResponse struct {
	Proofs []map[string]any `json:"proofs"`
}

// ============================================================================
// Other
// ============================================================================

// ChatIdDiscoveryPollResponse Chat ID discovery poll result
type ChatIdDiscoveryPollResponse struct {
	Status string `json:"status"`
	ChatID *string `json:"chat_id,omitempty"`
}

// ChatIdDiscoveryResponse Chat ID discovery token and Telegram deeplink
type ChatIdDiscoveryResponse struct {
	Token string `json:"token"`
	DeepLink string `json:"deep_link"`
	QRCode string `json:"qr_code"`
	ExpiresIn int `json:"expires_in"`
}

// ConfirmationStatus represents the possible values for confirmation status.
type ConfirmationStatus = string

// HitlChannelType represents the possible values for hitl channel type.
type HitlChannelType = string

// HitlChannel A messaging channel configured for HITL approvals
type HitlChannel struct {
	Type HitlChannelType `json:"type"`
	Config map[string]any `json:"config"`
}

// CreateHitlBody Request body for creating a HITL configuration
type CreateHitlBody struct {
	Name string `json:"name"`
	Channels []HitlChannel `json:"channels"`
	TimeoutSeconds *float64 `json:"timeout_seconds,omitempty"`
}

// HitlStatus represents the possible values for hitl status.
type HitlStatus = string

// HitlListQuery Query parameters for listing HITL configurations
type HitlListQuery struct {
	Page *int `json:"page,omitempty"`
	Limit *int `json:"limit,omitempty"`
	Status *HitlStatus `json:"status,omitempty"`
}

// Confirmation A HITL confirmation request
type Confirmation struct {
	ID ObjectId `json:"id"`
	HitlID any `json:"hitl_id"`
	Message string `json:"message"`
	Metadata map[string]any `json:"metadata,omitempty"`
	Status ConfirmationStatus `json:"status"`
	TimeoutSeconds int `json:"timeout_seconds"`
	Response map[string]any `json:"response,omitempty"`
	TimeoutAt *string `json:"timeout_at,omitempty"`
	ProofToken *string `json:"proof_token,omitempty"`
	ResolvedAt *string `json:"resolved_at,omitempty"`
	Environment string `json:"environment"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

// ConfirmationListQuery Query parameters for listing confirmations
type ConfirmationListQuery struct {
	Page *int `json:"page,omitempty"`
	Limit *int `json:"limit,omitempty"`
	Status *ConfirmationStatus `json:"status,omitempty"`
	HitlID *ObjectId `json:"hitl_id,omitempty"`
}

// ConfirmationListResponse Paginated list of confirmations
type ConfirmationListResponse struct {
	Data []Confirmation `json:"data"`
	Pagination map[string]any `json:"pagination"`
}

// CreateConfirmationBody Request body for creating a confirmation
type CreateConfirmationBody struct {
	HitlID any `json:"hitl_id"`
	Message string `json:"message"`
	ProofExpiryDays *int `json:"proof_expiry_days,omitempty"`
}

// Hitl HITL configuration with messaging channels and timeout
type Hitl struct {
	ID ObjectId `json:"id"`
	Name *string `json:"name,omitempty"`
	ProfileID any `json:"profile_id,omitempty"`
	Channels []HitlChannel `json:"channels"`
	TimeoutSeconds int `json:"timeout_seconds"`
	Status HitlStatus `json:"status"`
	Keypair map[string]any `json:"keypair"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

// HitlAuthorizationResponse Response from requesting authorization consent for HITL channels
type HitlAuthorizationResponse struct {
	HitlID ObjectId `json:"hitl_id"`
	Results []map[string]any `json:"results"`
	Message string `json:"message"`
}

// HitlListResponse Paginated list of HITL configurations
type HitlListResponse struct {
	Data []Hitl `json:"data"`
	Pagination map[string]any `json:"pagination"`
}

// UpdateHitlBody Request body for updating a HITL configuration
type UpdateHitlBody struct {
	Name *string `json:"name,omitempty"`
	Channels []HitlChannel `json:"channels,omitempty"`
	TimeoutSeconds *float64 `json:"timeout_seconds,omitempty"`
}

// ============================================================================
// Profiles
// ============================================================================

// ClaimUsernameRequest Request body for claiming a username
type ClaimUsernameRequest struct {
	Username string `json:"username"`
}

// CustomLink Custom link on a public profile
type CustomLink struct {
	Title string `json:"title"`
	URL string `json:"url"`
	Icon *string `json:"icon,omitempty"`
	IsVisible *bool `json:"is_visible,omitempty"`
	DisplayOrder *int `json:"display_order,omitempty"`
}

type ProfileIdParam struct {
	ProfileID string `json:"profileId"`
}

// ProfileProofEntry Proof display configuration for a profile
type ProfileProofEntry struct {
	AssetID string `json:"asset_id"`
	IsVisible *bool `json:"is_visible,omitempty"`
	MaskLevel *string `json:"mask_level,omitempty"`
	DisplayOrder *int `json:"display_order,omitempty"`
	Label *string `json:"label,omitempty"`
}

// ProfileTheme Profile theme customization
type ProfileTheme struct {
	PrimaryColor *string `json:"primary_color,omitempty"`
	BackgroundType *string `json:"background_type,omitempty"`
	BackgroundColor *string `json:"background_color,omitempty"`
	GradientStart *string `json:"gradient_start,omitempty"`
	GradientEnd *string `json:"gradient_end,omitempty"`
	FontStyle *string `json:"font_style,omitempty"`
}

// CreateProfileRequest Request body for creating a new profile
type CreateProfileRequest struct {
	DisplayName *string `json:"display_name,omitempty"`
	Bio *string `json:"bio,omitempty"`
	AvatarURL *string `json:"avatar_url,omitempty"`
	BusinessName *string `json:"business_name,omitempty"`
	IsBusiness *bool `json:"is_business,omitempty"`
	IsPublic *bool `json:"is_public,omitempty"`
	IsPrimary *bool `json:"is_primary,omitempty"`
	Theme *ProfileTheme `json:"theme,omitempty"`
}

// UpdateProfileProofsRequest Request body for updating which proofs are displayed on a profile
type UpdateProfileProofsRequest struct {
	Proofs []ProfileProofEntry `json:"proofs"`
}

// UpdateProfileRequest Request body for updating a profile
type UpdateProfileRequest struct {
	DisplayName *string `json:"display_name,omitempty"`
	Bio *string `json:"bio,omitempty"`
	AvatarURL *string `json:"avatar_url,omitempty"`
	BusinessName *string `json:"business_name,omitempty"`
	IsBusiness *bool `json:"is_business,omitempty"`
	IsPublic *bool `json:"is_public,omitempty"`
	IsPrimary *bool `json:"is_primary,omitempty"`
	ShowVerificationDates *bool `json:"show_verification_dates,omitempty"`
	ShowProofChannels *bool `json:"show_proof_channels,omitempty"`
	Theme *ProfileTheme `json:"theme,omitempty"`
	CustomLinks []CustomLink `json:"custom_links,omitempty"`
}

type UsernameParam struct {
	Username string `json:"username"`
}

// PublicProfile Public profile
type PublicProfile struct {
	ID ObjectId `json:"id"`
	DisplayName *string `json:"display_name,omitempty"`
	Bio *string `json:"bio,omitempty"`
	AvatarURL *string `json:"avatar_url,omitempty"`
	BusinessName *string `json:"business_name,omitempty"`
	IsBusiness *bool `json:"is_business,omitempty"`
	IsPublic bool `json:"is_public"`
	IsPrimary *bool `json:"is_primary,omitempty"`
	Username *string `json:"username,omitempty"`
	Theme *ProfileTheme `json:"theme,omitempty"`
	CustomLinks []CustomLink `json:"custom_links,omitempty"`
	Proofs []map[string]any `json:"proofs,omitempty"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

// ============================================================================
// API Keys
// ============================================================================

// CreateAPIKeyRequest Request body for creating an API key
type CreateAPIKeyRequest struct {
	Name *string `json:"name,omitempty"`
	Environment *string `json:"environment,omitempty"`
	Scopes []string `json:"scopes,omitempty"`
}

// APIKeyResponse API key (key value only shown on creation)
type APIKeyResponse struct {
	ID ObjectId `json:"id"`
	Name string `json:"name"`
	KeyPrefix string `json:"key_prefix"`
	Environment string `json:"environment"`
	Scopes []string `json:"scopes"`
	CreatedAt string `json:"created_at"`
	LastUsedAt *string `json:"last_used_at,omitempty"`
}

// ============================================================================
// DNS Credentials
// ============================================================================

// CreateProviderCredentialRequest Request body for creating stored DNS provider credentials
type CreateProviderCredentialRequest struct {
	Provider string `json:"provider"`
	Credentials map[string]any `json:"credentials"`
}

// ============================================================================
// Sessions
// ============================================================================

// CreateSessionRequest Request body for creating a phone verification session
type CreateSessionRequest struct {
	Phone string `json:"phone"`
	Channel *string `json:"channel,omitempty"`
}

// Session Phone verification session
type Session struct {
	ID ObjectId `json:"id"`
	Status string `json:"status"`
	Challenge *Challenge `json:"challenge,omitempty"`
	Proof *Proof `json:"proof,omitempty"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

// SessionChannel represents the possible values for session channel.
type SessionChannel = string

type SessionIdParam struct {
	ID string `json:"id"`
}

// ============================================================================
// Account
// ============================================================================

// DeleteAccountRequest Request body for final account deletion
type DeleteAccountRequest struct {
	SessionID string `json:"session_id"`
}

// InitiateAccountDeletionRequest Request body for initiating account deletion
type InitiateAccountDeletionRequest struct {
	Channel *string `json:"channel,omitempty"`
}

// ============================================================================
// Verified Users
// ============================================================================

type ExternalUserIdParam struct {
	ExternalUserID string `json:"externalUserId"`
}

// VerifiedUserDetail Detailed verification info for a specific external user
type VerifiedUserDetail struct {
	ExternalUserID string `json:"external_user_id"`
	VerificationCount int `json:"verification_count"`
	TypesVerified []VerificationType `json:"types_verified"`
	Verifications []map[string]any `json:"verifications"`
}

// VerifiedUserSummary Aggregated verification summary for an external user
type VerifiedUserSummary struct {
	ExternalUserID string `json:"external_user_id"`
	VerificationCount int `json:"verification_count"`
	TypesVerified []VerificationType `json:"types_verified"`
	Verifications []map[string]any `json:"verifications"`
	FirstVerifiedAt *string `json:"first_verified_at,omitempty"`
	LastVerifiedAt *string `json:"last_verified_at,omitempty"`
}

// VerifiedUserListResponse Paginated list of verified users
type VerifiedUserListResponse struct {
	Data []VerifiedUserSummary `json:"data"`
	Pagination map[string]any `json:"pagination"`
}

// ============================================================================
// Proofs
// ============================================================================

// JWK JSON Web Key
type JWK struct {
	Kty string `json:"kty"`
	N string `json:"n"`
	E string `json:"e"`
	Use string `json:"use"`
	Alg string `json:"alg"`
	Kid string `json:"kid"`
}

// JWKS JSON Web Key Set for offline proof verification
type JWKS struct {
	Keys []JWK `json:"keys"`
}

// Proof Proof token after successful verification
type Proof struct {
	Token string `json:"token"`
	ExpiresAt string `json:"expires_at"`
}

// RevokeProofRequest Request body for revoking a proof
type RevokeProofRequest struct {
	Reason any `json:"reason,omitempty"`
}

type RevokeProofResponse struct {
	Success bool `json:"success"`
	RevokedAt string `json:"revoked_at"`
}

// RevokedProof Entry in the revocation list
type RevokedProof struct {
	ProofID string `json:"proof_id"`
	RevokedAt string `json:"revoked_at"`
	Reason RevocationReason `json:"reason"`
}

// RevocationList Signed list of revoked proofs
type RevocationList struct {
	Revoked []RevokedProof `json:"revoked,omitempty"`
	GeneratedAt *string `json:"generated_at,omitempty"`
	Signature *string `json:"signature,omitempty"`
}

// ValidateProofRequest Request body for validating a proof token
type ValidateProofRequest struct {
	ProofToken string `json:"proof_token"`
}

// ProofStatusResponse Proof status check result
type ProofStatusResponse struct {
	ProofID ObjectId `json:"proof_id"`
	Status VerificationStatus `json:"status"`
	IsValid bool `json:"is_valid"`
	IsRevoked bool `json:"is_revoked"`
	RevokedAt *string `json:"revoked_at"`
	RevokedReason *string `json:"revoked_reason"`
	ExpiresAt *string `json:"expires_at"`
	IsExpired bool `json:"is_expired"`
}

// ValidateProofResponse Proof validation result. Returns verification details when valid, or reason/message when invalid.
type ValidateProofResponse struct {
	Valid bool `json:"valid"`
	Verification map[string]any `json:"verification,omitempty"`
	Reason *string `json:"reason,omitempty"`
	Message *string `json:"message,omitempty"`
	RevokedAt *string `json:"revoked_at,omitempty"`
	RevokedReason *string `json:"revoked_reason,omitempty"`
}

// ============================================================================
// Templates
// ============================================================================

// MessageType represents the possible values for message type.
type MessageType = string

// TemplateChannel represents the possible values for template channel.
type TemplateChannel = string

type ChannelTypeParam struct {
	ID ObjectId `json:"id"`
	Channel TemplateChannel `json:"channel"`
	Type MessageType `json:"type"`
}

// Template Message template
type Template struct {
	ID *ObjectId `json:"id,omitempty"`
	Channel TemplateChannel `json:"channel"`
	MessageType MessageType `json:"message_type"`
	Subject *string `json:"subject,omitempty"`
	Body string `json:"body"`
	ButtonText *string `json:"button_text,omitempty"`
	ButtonURLTemplate *string `json:"button_url_template,omitempty"`
	IsActive *bool `json:"is_active,omitempty"`
	Version *int `json:"version,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// TemplateContent Template content fields
type TemplateContent struct {
	Subject *string `json:"subject,omitempty"`
	Body string `json:"body"`
	ButtonText *string `json:"button_text,omitempty"`
	ButtonURLTemplate *string `json:"button_url_template,omitempty"`
}

type TemplatePathParam struct {
	Channel TemplateChannel `json:"channel"`
	MessageType MessageType `json:"messageType"`
}

// TemplatePreviewRequest Request body for previewing a template
type TemplatePreviewRequest struct {
	Channel TemplateChannel `json:"channel"`
	MessageType MessageType `json:"message_type"`
	Subject *string `json:"subject,omitempty"`
	Body string `json:"body"`
	ButtonText *string `json:"button_text,omitempty"`
	ButtonURLTemplate *string `json:"button_url_template,omitempty"`
}

// TemplateRenderRequest Request body for rendering a template with variables
type TemplateRenderRequest struct {
	Channel TemplateChannel `json:"channel"`
	MessageType MessageType `json:"message_type"`
	Variables map[string]any `json:"variables,omitempty"`
}

// TemplateVariable Available template variable
type TemplateVariable struct {
	Name string `json:"name"`
	Description string `json:"description"`
}

// ============================================================================
// Projects
// ============================================================================

// ProjectBranding Project branding settings
type ProjectBranding struct {
	BusinessName *string `json:"business_name,omitempty"`
	LogoURL *string `json:"logo_url,omitempty"`
	PrimaryColor *string `json:"primary_color,omitempty"`
	SupportEmail *string `json:"support_email,omitempty"`
}

// CreateProjectRequest Request body for creating a project
type CreateProjectRequest struct {
	Name string `json:"name"`
	Description *string `json:"description,omitempty"`
	Branding *ProjectBranding `json:"branding,omitempty"`
}

// ProjectCallbacks Project callback URLs
type ProjectCallbacks struct {
	SuccessURL *string `json:"success_url,omitempty"`
	FailureURL *string `json:"failure_url,omitempty"`
	CancelURL *string `json:"cancel_url,omitempty"`
}

// Project Project
type Project struct {
	ID ObjectId `json:"id"`
	Name string `json:"name"`
	Description *string `json:"description,omitempty"`
	Branding *ProjectBranding `json:"branding,omitempty"`
	Callbacks *ProjectCallbacks `json:"callbacks,omitempty"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

// UpdateProjectRequest Request body for updating a project
type UpdateProjectRequest struct {
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Branding *ProjectBranding `json:"branding,omitempty"`
	Callbacks *ProjectCallbacks `json:"callbacks,omitempty"`
}

// ============================================================================
// Verify Flow
// ============================================================================

// StartAssetVerificationRequest Request body for starting asset verification in a verification request
type StartAssetVerificationRequest struct {
	Channel string `json:"channel"`
	Identifier *string `json:"identifier,omitempty"`
	BotToken *string `json:"bot_token,omitempty"`
}

// TryItRequest Request body for creating a demo verification request
type TryItRequest struct {
	Type string `json:"type"`
	Identifier string `json:"identifier"`
}

// ============================================================================
// 2FA
// ============================================================================

// TwoFAActionType represents the possible values for two fa action type.
type TwoFAActionType = string

// Start2FARequest Request body for starting 2FA verification
type Start2FARequest struct {
	ActionType TwoFAActionType `json:"action_type"`
	Channel string `json:"channel"`
	EmailID *string `json:"email_id,omitempty"`
}

// ============================================================================
// Webhook Deliveries
// ============================================================================

// WebhookDeliveryStats Webhook delivery statistics
type WebhookDeliveryStats struct {
	Total int `json:"total"`
	Delivered int `json:"delivered"`
	Failed int `json:"failed"`
	Pending int `json:"pending"`
	SuccessRate float64 `json:"success_rate"`
}

// WebhookDeliveryStatus represents the possible values for webhook delivery status.
type WebhookDeliveryStatus = string

// WebhookEventType represents the possible values for webhook event type.
type WebhookEventType = string

// WebhookDelivery Webhook delivery record
type WebhookDelivery struct {
	ID ObjectId `json:"id"`
	VerificationRequestID *ObjectId `json:"verification_request_id,omitempty"`
	EventType WebhookEventType `json:"event_type"`
	URL string `json:"url"`
	Status WebhookDeliveryStatus `json:"status"`
	Attempts int `json:"attempts"`
	MaxAttempts int `json:"max_attempts"`
	LastAttemptAt *string `json:"last_attempt_at,omitempty"`
	NextRetryAt *string `json:"next_retry_at,omitempty"`
	ResponseStatus *int `json:"response_status,omitempty"`
	ResponseBody *string `json:"response_body,omitempty"`
	ErrorMessage *string `json:"error_message,omitempty"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type RetryDeliveryResponse struct {
	Success bool `json:"success"`
	Delivery WebhookDelivery `json:"delivery"`
}

type WebhookDeliveryListQuery struct {
	Page *int `json:"page,omitempty"`
	Limit *int `json:"limit,omitempty"`
	Status *WebhookDeliveryStatus `json:"status,omitempty"`
	EventType *WebhookEventType `json:"event_type,omitempty"`
	VerificationRequestID any `json:"verification_request_id,omitempty"`
}

type WebhookDeliveryListResponse struct {
	Data []WebhookDelivery `json:"data"`
	Pagination map[string]any `json:"pagination"`
}

// WebhookProof Proof of a verified asset included in webhook payload
type WebhookProof struct {
	Type VerificationType `json:"type"`
	Identifier string `json:"identifier"`
	VerifiedAt *string `json:"verified_at,omitempty"`
	Channel VerificationChannel `json:"channel"`
	ProofToken *string `json:"proof_token,omitempty"`
}

// WebhookPayload Outbound webhook payload sent to callback URLs on verification/confirmation events
type WebhookPayload struct {
	Event WebhookEventType `json:"event"`
	RequestID ObjectId `json:"request_id"`
	ReferenceID *string `json:"reference_id,omitempty"`
	Status VerificationRequestStatus `json:"status"`
	ActionType ActionType `json:"action_type"`
	ActionContext *ActionContext `json:"action_context,omitempty"`
	ClientMetadata map[string]any `json:"client_metadata,omitempty"`
	CompletedAt *string `json:"completed_at,omitempty"`
	Proofs []WebhookProof `json:"proofs"`
	Progress map[string]any `json:"progress"`
	Test *bool `json:"test,omitempty"`
}

// ============================================================================
// Enum Constants
// ============================================================================

const (
	RevocationReasonUserRequest RevocationReason = "user_request"
	RevocationReasonFraud RevocationReason = "fraud"
	RevocationReasonKeyCompromise RevocationReason = "key_compromise"
	RevocationReasonAssetTransferred RevocationReason = "asset_transferred"
	RevocationReasonOther RevocationReason = "other"
)

const (
	ActionTypeVerification ActionType = "verification"
	ActionType2fa ActionType = "2fa"
	ActionTypeLogin ActionType = "login"
	ActionTypeCustom ActionType = "custom"
	ActionTypeConfirmation ActionType = "confirmation"
	ActionTypeAuthorization ActionType = "authorization"
)

const (
	DomainStatusPending DomainStatus = "pending"
	DomainStatusVerified DomainStatus = "verified"
	DomainStatusFailed DomainStatus = "failed"
)

const (
	AssetStatusActive AssetStatus = "active"
	AssetStatusExpired AssetStatus = "expired"
	AssetStatusRevoked AssetStatus = "revoked"
)

const (
	AuthChannelTelegram AuthChannel = "telegram"
	AuthChannelWhatsapp AuthChannel = "whatsapp"
	AuthChannelSms AuthChannel = "sms"
	AuthChannelEmail AuthChannel = "email"
)

const (
	AuthSessionStatusPending AuthSessionStatus = "pending"
	AuthSessionStatusVerified AuthSessionStatus = "verified"
	AuthSessionStatusExpired AuthSessionStatus = "expired"
)

const (
	AuthorizationChannelWhatsapp AuthorizationChannel = "whatsapp"
	AuthorizationChannelTelegram AuthorizationChannel = "telegram"
	AuthorizationChannelSms AuthorizationChannel = "sms"
	AuthorizationChannelEmail AuthorizationChannel = "email"
)

const (
	AuthorizationScopeConfirmations AuthorizationScope = "confirmations"
)

const (
	AuthorizationStatusPending AuthorizationStatus = "pending"
	AuthorizationStatusActive AuthorizationStatus = "active"
	AuthorizationStatusExpired AuthorizationStatus = "expired"
	AuthorizationStatusRevoked AuthorizationStatus = "revoked"
	AuthorizationStatusDenied AuthorizationStatus = "denied"
)

const (
	BillingPlanPro BillingPlan = "pro"
	BillingPlanBusiness BillingPlan = "business"
	BillingPlanWhiteLabel BillingPlan = "white_label"
	BillingPlanEnterprise BillingPlan = "enterprise"
)

const (
	VerificationChannelWhatsapp VerificationChannel = "whatsapp"
	VerificationChannelTelegram VerificationChannel = "telegram"
	VerificationChannelViber VerificationChannel = "viber"
	VerificationChannelSms VerificationChannel = "sms"
	VerificationChannelEmail VerificationChannel = "email"
	VerificationChannelDns VerificationChannel = "dns"
	VerificationChannelHttp VerificationChannel = "http"
	VerificationChannelAuto VerificationChannel = "auto"
	VerificationChannelGithub VerificationChannel = "github"
	VerificationChannelGoogle VerificationChannel = "google"
	VerificationChannelFacebook VerificationChannel = "facebook"
	VerificationChannelX VerificationChannel = "x"
	VerificationChannelLinkedin VerificationChannel = "linkedin"
	VerificationChannelInstagram VerificationChannel = "instagram"
	VerificationChannelYoutube VerificationChannel = "youtube"
	VerificationChannelTiktok VerificationChannel = "tiktok"
	VerificationChannelEthereum VerificationChannel = "ethereum"
	VerificationChannelSolana VerificationChannel = "solana"
	VerificationChannelBitcoin VerificationChannel = "bitcoin"
	VerificationChannelCoinbase VerificationChannel = "coinbase"
	VerificationChannelKraken VerificationChannel = "kraken"
	VerificationChannelTelegramBotToken VerificationChannel = "telegram_bot_token"
)

const (
	VerificationRequestStatusPending VerificationRequestStatus = "pending"
	VerificationRequestStatusPartial VerificationRequestStatus = "partial"
	VerificationRequestStatusCompleted VerificationRequestStatus = "completed"
	VerificationRequestStatusExpired VerificationRequestStatus = "expired"
	VerificationRequestStatusCancelled VerificationRequestStatus = "cancelled"
)

const (
	VerificationStatusPending VerificationStatus = "pending"
	VerificationStatusVerified VerificationStatus = "verified"
	VerificationStatusFailed VerificationStatus = "failed"
	VerificationStatusExpired VerificationStatus = "expired"
	VerificationStatusRevoked VerificationStatus = "revoked"
)

const (
	VerificationTypePhone VerificationType = "phone"
	VerificationTypeEmail VerificationType = "email"
	VerificationTypeDomain VerificationType = "domain"
	VerificationTypeSocial VerificationType = "social"
	VerificationTypeWallet VerificationType = "wallet"
	VerificationTypeAccount VerificationType = "account"
	VerificationTypeTelegramBot VerificationType = "telegram_bot"
)

const (
	ConfirmationStatusPending ConfirmationStatus = "pending"
	ConfirmationStatusApproved ConfirmationStatus = "approved"
	ConfirmationStatusDenied ConfirmationStatus = "denied"
)

const (
	HitlChannelTypeTelegram HitlChannelType = "telegram"
	HitlChannelTypeWhatsapp HitlChannelType = "whatsapp"
	HitlChannelTypeBrowser HitlChannelType = "browser"
)

const (
	HitlStatusActive HitlStatus = "active"
	HitlStatusArchived HitlStatus = "archived"
)

const (
	SessionChannelTelegram SessionChannel = "telegram"
	SessionChannelWhatsapp SessionChannel = "whatsapp"
	SessionChannelViber SessionChannel = "viber"
	SessionChannelSms SessionChannel = "sms"
)

const (
	MessageTypeVerificationRequest MessageType = "verification_request"
	MessageTypeVerificationSuccess MessageType = "verification_success"
	MessageTypeVerificationExpired MessageType = "verification_expired"
	MessageTypeLoginRequest MessageType = "login_request"
	MessageTypeLoginSuccess MessageType = "login_success"
	MessageType2faRequest MessageType = "2fa_request"
	MessageType2faSuccess MessageType = "2fa_success"
)

const (
	TemplateChannelTelegram TemplateChannel = "telegram"
	TemplateChannelWhatsapp TemplateChannel = "whatsapp"
	TemplateChannelSms TemplateChannel = "sms"
	TemplateChannelEmail TemplateChannel = "email"
)

const (
	TwoFAActionTypeApiKeyView TwoFAActionType = "api_key_view"
	TwoFAActionTypeApiKeyCreate TwoFAActionType = "api_key_create"
	TwoFAActionTypeApiKeyRevoke TwoFAActionType = "api_key_revoke"
	TwoFAActionTypeApiKeyRegenerate TwoFAActionType = "api_key_regenerate"
	TwoFAActionTypePhoneAdd TwoFAActionType = "phone_add"
	TwoFAActionTypePhoneRemove TwoFAActionType = "phone_remove"
	TwoFAActionTypeEmailAdd TwoFAActionType = "email_add"
	TwoFAActionTypeEmailRemove TwoFAActionType = "email_remove"
	TwoFAActionTypeAccountDelete TwoFAActionType = "account_delete"
)

const (
	WebhookDeliveryStatusPending WebhookDeliveryStatus = "pending"
	WebhookDeliveryStatusDelivered WebhookDeliveryStatus = "delivered"
	WebhookDeliveryStatusFailed WebhookDeliveryStatus = "failed"
)

const (
	WebhookEventTypeVerificationRequestCompleted WebhookEventType = "verification_request.completed"
	WebhookEventTypeVerificationRequestPartial WebhookEventType = "verification_request.partial"
	WebhookEventTypeVerificationRequestExpired WebhookEventType = "verification_request.expired"
	WebhookEventTypeVerificationCompleted WebhookEventType = "verification.completed"
	WebhookEventTypeConfirmationApproved WebhookEventType = "confirmation.approved"
	WebhookEventTypeConfirmationDenied WebhookEventType = "confirmation.denied"
	WebhookEventTypeProofRevoked WebhookEventType = "proof.revoked"
)
