// Code generated by scripts/generate-sdk-types.ts. DO NOT EDIT.
//
// Source: npm run sdk:generate-types
// Generated from OpenAPI spec via src/openapi/registry.ts

package proof

// ============================================================================
// Common
// ============================================================================

type APIInfo struct {
	Name string `json:"name"`
	Version string `json:"version"`
	Description string `json:"description"`
	Links map[string]any `json:"links"`
}

// ErrorDetail Field-level validation error detail
type ErrorDetail struct {
	Field string `json:"field"`
	Message string `json:"message"`
	Code string `json:"code"`
}

// ErrorResponse Standard error response format
type ErrorResponse struct {
	Error map[string]any `json:"error"`
}

// HealthResponse Detailed health check response
type HealthResponse struct {
	Status string `json:"status"`
	Timestamp any `json:"timestamp"`
}

// LivenessResponse Liveness probe response — always returns ok if the process is alive
type LivenessResponse struct {
	Status string `json:"status"`
	Timestamp string `json:"timestamp"`
}

type ObjectId = string

type IdParam struct {
	ID ObjectId `json:"id"`
}

// PaginationResponse Pagination info in list responses
type PaginationResponse struct {
	Page *int `json:"page,omitempty"`
	Limit *int `json:"limit,omitempty"`
	Total *int `json:"total,omitempty"`
	TotalPages *int `json:"total_pages,omitempty"`
}

// RevocationReason represents the possible values for revocation reason.
type RevocationReason = string

// SuccessResponse Generic success response
type SuccessResponse struct {
	Success bool `json:"success"`
	Message *string `json:"message,omitempty"`
}

// ============================================================================
// Other
// ============================================================================

type AccountSessionIdParam struct {
	ID string `json:"id"`
}

// AccountSessionType represents the possible values for account session type.
type AccountSessionType = string

// AccountSummary One-call account snapshot for the dashboard home and AI agents
type AccountSummary struct {
	AsOf string `json:"as_of"`
	CacheAgeSeconds float64 `json:"cache_age_seconds"`
	Quota map[string]any `json:"quota"`
	RequestHealth map[string]any `json:"request_health"`
	TopChannels []map[string]any `json:"top_channels"`
	ChannelsWithZeroCompletions []string `json:"channels_with_zero_completions"`
	HitlChannels map[string]any `json:"hitl_channels,omitempty"`
	ActiveAPIKeys float64 `json:"active_api_keys"`
	NextAction map[string]any `json:"next_action"`
}

// AddCircleMemberChannelBody Request body for declaring a channel for a Circle member
type AddCircleMemberChannelBody struct {
	Channel string `json:"channel"`
	Identifier string `json:"identifier"`
}

// ApiKeyUsageQueryParams Per-API-key usage query parameters
type ApiKeyUsageQueryParams struct {
	Environment *string `json:"environment,omitempty"`
}

// ApprovalLinkResponse Regenerated approval link for a pending confirmation
type ApprovalLinkResponse struct {
	ApprovalURL string `json:"approval_url"`
}

// AssetChannel represents the possible values for asset channel.
type AssetChannel = string

// AccountSessionResponse Account-session response. Same wire format whether the request created a new account or pivoted to login — the `type` field distinguishes the outcome.
type AccountSessionResponse struct {
	ID string `json:"id"`
	Type AccountSessionType `json:"type"`
	Channel AuthChannel `json:"channel"`
	Status AuthSessionStatus `json:"status"`
	DeepLink *string `json:"deep_link,omitempty"`
	QRCode *string `json:"qr_code,omitempty"`
	QRText *string `json:"qr_text,omitempty"`
	SmsCode *string `json:"sms_code,omitempty"`
	SmsMessage *string `json:"sms_message,omitempty"`
	Email *string `json:"email,omitempty"`
	EmailSent *bool `json:"email_sent,omitempty"`
	EmailError *string `json:"email_error,omitempty"`
	ExpiresAt string `json:"expires_at"`
	Instructions *string `json:"instructions,omitempty"`
	VerifiedAt *string `json:"verified_at,omitempty"`
	UserID *string `json:"user_id,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
}

// ChatIdDiscoveryPollResponse Chat ID discovery poll result
type ChatIdDiscoveryPollResponse struct {
	Status string `json:"status"`
	ChatID *string `json:"chat_id,omitempty"`
}

// ChatIdDiscoveryResponse Chat ID discovery token and Telegram deeplink
type ChatIdDiscoveryResponse struct {
	Token string `json:"token"`
	DeepLink string `json:"deep_link"`
	QRCode string `json:"qr_code"`
	QRText string `json:"qr_text"`
	ExpiresIn int `json:"expires_in"`
}

// CircleMemberInput A Circle member to create (name + optional declared channels)
type CircleMemberInput struct {
	Name string `json:"name"`
	TelegramChatID *string `json:"telegram_chat_id,omitempty"`
	WhatsappPhone *string `json:"whatsapp_phone,omitempty"`
}

// CircleStatus represents the possible values for circle status.
type CircleStatus = string

// ConfirmationStatus represents the possible values for confirmation status.
type ConfirmationStatus = string

// ConfirmationStatusFilter represents the possible values for confirmation status filter.
type ConfirmationStatusFilter = string

// CreateAccountRequest Request body for creating an account-bootstrap session. The server transparently pivots to a login session when the submitted identity already belongs to an active User, so the agent polls identically regardless of outcome.
type CreateAccountRequest struct {
	Channel AuthChannel `json:"channel"`
	PhoneNumber *string `json:"phone_number,omitempty"`
	Email *string `json:"email,omitempty"`
}

// CreateCircleMemberBody Request body for adding a member to a Circle
type CreateCircleMemberBody struct {
	Name string `json:"name"`
	WhatsappPhone *string `json:"whatsapp_phone,omitempty"`
}

// DelegateIdentifier Typed delegate identifier
type DelegateIdentifier struct {
	Type string `json:"type"`
	Value string `json:"value"`
}

// CreateDelegationRequest Create a delegation from a proven domain to an artifact
type CreateDelegationRequest struct {
	ControlProof string `json:"control_proof"`
	Delegate DelegateIdentifier `json:"delegate"`
	Scope []string `json:"scope"`
	ExpiresIn *int `json:"expires_in,omitempty"`
}

// HitlChannel is a discriminated union — use map for flexibility.
type HitlChannel = map[string]any

// HitlChannelType represents the possible values for hitl channel type.
type HitlChannelType = string

// HitlStatus represents the possible values for hitl status.
type HitlStatus = string

// HitlListQuery Query parameters for listing HITL configurations
type HitlListQuery struct {
	Page *int `json:"page,omitempty"`
	Limit *int `json:"limit,omitempty"`
	Status *HitlStatus `json:"status,omitempty"`
	Environment *string `json:"environment,omitempty"`
	ProfileID *string `json:"profile_id,omitempty"`
}

// IdentityChallengeCreate Create a cross-channel identity challenge (Proof of Me)
type IdentityChallengeCreate struct {
	CircleID string `json:"circle_id"`
	MemberID string `json:"member_id"`
	SuspiciousChannel *string `json:"suspicious_channel,omitempty"`
}

// IdentityChallengeResponse An identity challenge (Proof of Me)
type IdentityChallengeResponse struct {
	ID string `json:"id"`
	Status string `json:"status"`
	Channel *string `json:"channel,omitempty"`
	ConfirmChannel *string `json:"confirm_channel,omitempty"`
	SingleChannelWarning *bool `json:"single_channel_warning,omitempty"`
	CircleID *string `json:"circle_id,omitempty"`
	IsDrill *bool `json:"is_drill,omitempty"`
	ProofID *string `json:"proof_id,omitempty"`
	ProofToken *string `json:"proof_token,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	ResolvedAt *string `json:"resolved_at,omitempty"`
	ExpiresAt *string `json:"expires_at,omitempty"`
}

// IdentityChallengeListResponse Identity challenges, newest first
type IdentityChallengeListResponse struct {
	Data []IdentityChallengeResponse `json:"data"`
	Pagination map[string]any `json:"pagination"`
}

// LookalikeWatchSubscribe Subscribe to Lookalike Watch. `brand_tokens` are the names watched for confusable newly-published artifacts; `owned_namespaces` suppress alerts on artifacts you publish yourself; `notify_email` must be an address already proven on the account, because a subscription is a standing outbound channel rather than a one-shot send. Every bound is published on the fields themselves — restating a cap in prose is the second declaration this block exists to avoid.
type LookalikeWatchSubscribe struct {
	BrandTokens []string `json:"brand_tokens"`
	OwnedNamespaces []string `json:"owned_namespaces,omitempty"`
	NotifyEmail *string `json:"notify_email,omitempty"`
}

// MasterKeyResponse HITL master-key KDF salt for the authenticated user
type MasterKeyResponse struct {
	MasterKdfSalt *string `json:"master_kdf_salt"`
	BackupKdfSalt *string `json:"backup_kdf_salt"`
}

type McpConnectInfo struct {
	Message string `json:"message"`
	RemoteURL *string `json:"remote_url,omitempty"`
	RemoteConfig map[string]any `json:"remote_config,omitempty"`
	InstallCommand string `json:"install_command"`
	InstallCaveat string `json:"install_caveat"`
	ClientConfig map[string]any `json:"client_config"`
	DocsURL string `json:"docs_url"`
}

// MeAssetSearchQueryParams Universal asset search query parameters
type MeAssetSearchQueryParams struct {
	Value string `json:"value"`
	Type *string `json:"type,omitempty"`
	Environment *string `json:"environment,omitempty"`
}

// MeAssetSearchResponse Exact-match asset dossier. `*_masked` fields are always masked; the owner's JWT session additionally receives unmasked `identifier`/`recipient` twins — never returned to API-key callers (owner-vs-not boundary, SEC-001). Authorizations/confirmations require hitl:read for API-key callers; related records follow the provable verification_id -> authorization_id chain only.
type MeAssetSearchResponse struct {
	Data map[string]any `json:"data"`
	Total float64 `json:"total"`
}

// MeSearchQueryParams Account search query parameters
type MeSearchQueryParams struct {
	Q string `json:"q"`
	Type *string `json:"type,omitempty"`
	Environment *string `json:"environment,omitempty"`
	Limit *int `json:"limit,omitempty"`
}

// MeSearchResponse Account search results grouped by resource type. `masked_identifier` is always masked; the owner's JWT session additionally receives the unmasked `identifier` twin — never returned to API-key callers (owner-vs-not boundary, SEC-001). The hitl/confirmations buckets require the matching read scope.
type MeSearchResponse struct {
	Data map[string]any `json:"data"`
	Total float64 `json:"total"`
}

// MultiChannelPhoneChannel represents the possible values for multi channel phone channel.
type MultiChannelPhoneChannel = string

// CreateMultiChannelVerificationRequest Request body for creating a multi-channel verification group
type CreateMultiChannelVerificationRequest struct {
	Type string `json:"type"`
	Identifier string `json:"identifier"`
	Channels []MultiChannelPhoneChannel `json:"channels"`
	ExternalUserID *string `json:"external_user_id,omitempty"`
	ClientMetadata map[string]any `json:"client_metadata,omitempty"`
	ProofExpiryDays *int `json:"proof_expiry_days,omitempty"`
}

type OAuthAuthorizationServerMetadata struct {
	Issuer string `json:"issuer"`
	AuthorizationEndpoint string `json:"authorization_endpoint"`
	TokenEndpoint string `json:"token_endpoint"`
	RegistrationEndpoint string `json:"registration_endpoint"`
	RevocationEndpoint string `json:"revocation_endpoint"`
	ResponseTypesSupported []string `json:"response_types_supported"`
	GrantTypesSupported []string `json:"grant_types_supported"`
	CodeChallengeMethodsSupported []string `json:"code_challenge_methods_supported"`
	TokenEndpointAuthMethodsSupported []string `json:"token_endpoint_auth_methods_supported"`
	ScopesSupported []string `json:"scopes_supported"`
	ServiceDocumentation string `json:"service_documentation"`
}

type OAuthProtectedResourceMetadata struct {
	Resource string `json:"resource"`
	AuthorizationServers []string `json:"authorization_servers"`
	ScopesSupported []string `json:"scopes_supported"`
	BearerMethodsSupported []string `json:"bearer_methods_supported"`
	ResourceName string `json:"resource_name"`
	ResourceDocumentation string `json:"resource_documentation"`
}

// ApiKeyUsageResponse Per-API-key usage: verification counts by type/channel/status + per-collection totals (requests, confirmations, authorizations) + attribution metadata. Counts only — no recipient identifiers (SEC-001). Data is returned for revoked keys (audit).
type ApiKeyUsageResponse struct {
	APIKey map[string]any `json:"api_key"`
	Verifications map[string]any `json:"verifications"`
	VerificationRequests map[string]any `json:"verification_requests"`
	Confirmations map[string]any `json:"confirmations"`
	Authorizations map[string]any `json:"authorizations"`
	AttributionCutoffAt *string `json:"attribution_cutoff_at"`
	AttributedFraction *float64 `json:"attributed_fraction"`
}

type AvailableAssetsQuery struct {
	ProfileID any `json:"profile_id,omitempty"`
}

// CircleMember A Circle member (channel presence and a masked enrollment phone only, never an identifier)
type CircleMember struct {
	ID ObjectId `json:"id"`
	Name string `json:"name"`
	Status string `json:"status"`
	HasTelegram bool `json:"has_telegram"`
	HasWhatsapp bool `json:"has_whatsapp"`
	MeshOptedIn bool `json:"mesh_opted_in"`
	MeshOptOut bool `json:"mesh_opt_out"`
	EnrolledPhoneHint *string `json:"enrolled_phone_hint"`
	EnrolledAt *string `json:"enrolled_at"`
	LastVerifiedAt *string `json:"last_verified_at"`
}

// Circle A Circle — a named group of trusted contacts
type Circle struct {
	ID ObjectId `json:"id"`
	UserID *ObjectId `json:"user_id"`
	Name *string `json:"name"`
	OwnerName *string `json:"owner_name"`
	ProfileID *ObjectId `json:"profile_id"`
	Environment string `json:"environment"`
	ProofMeEnabled bool `json:"proof_me_enabled"`
	Status CircleStatus `json:"status"`
	MemberCount int `json:"member_count"`
	Members []CircleMember `json:"members"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

// CircleListResponse Paginated list of Circles
type CircleListResponse struct {
	Data []Circle `json:"data"`
	Pagination map[string]any `json:"pagination"`
}

// CircleMemberChannel A member channel (metadata only — never the identifier, SEC-PM-006)
type CircleMemberChannel struct {
	ID ObjectId `json:"id"`
	Channel string `json:"channel"`
	Status string `json:"status"`
	VerifiedAt *string `json:"verified_at"`
	CreatedAt string `json:"created_at"`
}

// CircleMemberChannelListResponse The channels of a Circle member
type CircleMemberChannelListResponse struct {
	Channels []CircleMemberChannel `json:"channels"`
}

// CircleMemberDrillResponse Result of manually triggering a member drill (Proof of Me)
type CircleMemberDrillResponse struct {
	ID any `json:"id"`
	Status string `json:"status"`
	ConfirmChannel *string `json:"confirm_channel,omitempty"`
	SingleChannelWarning *bool `json:"single_channel_warning,omitempty"`
}

// CircleMemberInviteBody Request body for inviting (enrolling) a Circle member
type CircleMemberInviteBody struct {
	MemberID any `json:"member_id"`
}

// CircleMemberInviteResponse A single-use member enrollment link (both channels + QR)
type CircleMemberInviteResponse struct {
	Token string `json:"token"`
	MemberID ObjectId `json:"member_id"`
	TelegramDeepLink string `json:"telegram_deep_link"`
	WhatsappDeepLink string `json:"whatsapp_deep_link"`
	QRCode string `json:"qr_code"`
	QRText string `json:"qr_text"`
	ExpiresIn int `json:"expires_in"`
	SuggestedShareText string `json:"suggested_share_text"`
}

// CircleMemberListResponse The members of a Circle
type CircleMemberListResponse struct {
	Members []CircleMember `json:"members"`
}

// Confirmation A HITL confirmation request
type Confirmation struct {
	ID ObjectId `json:"id"`
	HitlID any `json:"hitl_id"`
	Message string `json:"message"`
	Status ConfirmationStatus `json:"status"`
	Response map[string]any `json:"response,omitempty"`
	TimeoutAt *string `json:"timeout_at,omitempty"`
	ProofToken *string `json:"proof_token,omitempty"`
	ResolvedAt *string `json:"resolved_at,omitempty"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

// ConfirmationListQuery Query parameters for listing confirmations
type ConfirmationListQuery struct {
	Page *int `json:"page,omitempty"`
	Limit *int `json:"limit,omitempty"`
	Status *ConfirmationStatusFilter `json:"status,omitempty"`
	HitlID *ObjectId `json:"hitl_id,omitempty"`
	StartDate *string `json:"start_date,omitempty"`
	EndDate *string `json:"end_date,omitempty"`
}

// ConfirmationListResponse Paginated list of confirmations
type ConfirmationListResponse struct {
	Data []Confirmation `json:"data"`
	Pagination map[string]any `json:"pagination"`
}

// ConfirmationWebhookPayload Body of `confirmation.approved` / `confirmation.denied`. A timeout is `confirmation.denied` with `response.channel` `system` and `response.text` `timeout`.
type ConfirmationWebhookPayload struct {
	Event string `json:"event"`
	ConfirmationID ObjectId `json:"confirmation_id"`
	HitlID any `json:"hitl_id"`
	Status string `json:"status"`
	Message string `json:"message"`
	Response map[string]any `json:"response,omitempty"`
	ProofToken *string `json:"proof_token,omitempty"`
	Encrypted bool `json:"encrypted"`
	ResolvedAt *string `json:"resolved_at,omitempty"`
}

// CreateCircleBody Request body for creating a Circle
type CreateCircleBody struct {
	Name string `json:"name"`
	OwnerName *string `json:"owner_name,omitempty"`
	ProfileID any `json:"profile_id,omitempty"`
	ProofMeEnabled *bool `json:"proof_me_enabled,omitempty"`
	Members []CircleMemberInput `json:"members,omitempty"`
}

// CreateConfirmationBody Request body for creating a confirmation
type CreateConfirmationBody struct {
	HitlID any `json:"hitl_id"`
	Message string `json:"message"`
	ProofExpiryDays *int `json:"proof_expiry_days,omitempty"`
}

// CreateHitlBody Request body for creating a HITL configuration
type CreateHitlBody struct {
	Name string `json:"name"`
	Channels []HitlChannel `json:"channels,omitempty"`
	CircleID any `json:"circle_id,omitempty"`
	TimeoutSeconds *float64 `json:"timeout_seconds,omitempty"`
	ProfileID any `json:"profile_id,omitempty"`
}

// Delegation A delegation — link 2 of the proof chain: domain → artifact. NO endpoint returns this shape: every delegation response carries the derived `effective_status`/`is_valid` too, so read `DelegationListItem` (list, revoke) or `DelegationDetail` (create, get). Published as a back-compat type only.
type Delegation struct {
	ID ObjectId `json:"id"`
	DelegationID *string `json:"delegation_id"`
	Principal string `json:"principal"`
	Delegate DelegateIdentifier `json:"delegate"`
	Scope []string `json:"scope"`
	ControlProof string `json:"control_proof"`
	Status string `json:"status"`
	RevokedAt *string `json:"revoked_at"`
	RevokedReason *string `json:"revoked_reason"`
	Environment string `json:"environment"`
	IssuedAt string `json:"issued_at"`
	ExpiresAt string `json:"expires_at"`
	CreatedAt string `json:"created_at"`
}

// DelegationDetail A delegation with its derived effective status
type DelegationDetail struct {
	ID ObjectId `json:"id"`
	DelegationID *string `json:"delegation_id"`
	Principal string `json:"principal"`
	Delegate DelegateIdentifier `json:"delegate"`
	Scope []string `json:"scope"`
	ControlProof string `json:"control_proof"`
	Status string `json:"status"`
	RevokedAt *string `json:"revoked_at"`
	RevokedReason *string `json:"revoked_reason"`
	Environment string `json:"environment"`
	IssuedAt string `json:"issued_at"`
	ExpiresAt string `json:"expires_at"`
	CreatedAt string `json:"created_at"`
	Token *string `json:"token"`
	EffectiveStatus string `json:"effective_status"`
	IsValid bool `json:"is_valid"`
}

// DelegationListItem A delegation without its token, carrying stored status plus derived liveness — what the owner listing reports, and what `POST /delegations/{id}/revoke` answers with
type DelegationListItem struct {
	ID ObjectId `json:"id"`
	DelegationID *string `json:"delegation_id"`
	Principal string `json:"principal"`
	Delegate DelegateIdentifier `json:"delegate"`
	Scope []string `json:"scope"`
	ControlProof string `json:"control_proof"`
	Status string `json:"status"`
	RevokedAt *string `json:"revoked_at"`
	RevokedReason *string `json:"revoked_reason"`
	Environment string `json:"environment"`
	IssuedAt string `json:"issued_at"`
	ExpiresAt string `json:"expires_at"`
	CreatedAt string `json:"created_at"`
	EffectiveStatus string `json:"effective_status"`
	IsValid bool `json:"is_valid"`
}

// DelegationListResponse The caller's own delegations (no public enumeration exists)
type DelegationListResponse struct {
	Data []DelegationListItem `json:"data"`
	Pagination map[string]any `json:"pagination"`
}

// DelegationWithToken A delegation including its publishable signed token. NO endpoint returns this shape — `POST /delegations` and `GET /delegations/{id}` answer with `DelegationDetail`, which adds the derived `effective_status`/`is_valid`. Published as a back-compat type only.
type DelegationWithToken struct {
	ID ObjectId `json:"id"`
	DelegationID *string `json:"delegation_id"`
	Principal string `json:"principal"`
	Delegate DelegateIdentifier `json:"delegate"`
	Scope []string `json:"scope"`
	ControlProof string `json:"control_proof"`
	Status string `json:"status"`
	RevokedAt *string `json:"revoked_at"`
	RevokedReason *string `json:"revoked_reason"`
	Environment string `json:"environment"`
	IssuedAt string `json:"issued_at"`
	ExpiresAt string `json:"expires_at"`
	CreatedAt string `json:"created_at"`
	Token *string `json:"token"`
}

// Hitl HITL configuration with messaging channels and timeout
type Hitl struct {
	ID ObjectId `json:"id"`
	UserID *ObjectId `json:"user_id"`
	Name *string `json:"name,omitempty"`
	ProfileID *ObjectId `json:"profile_id,omitempty"`
	CircleID *ObjectId `json:"circle_id,omitempty"`
	Channels []HitlChannel `json:"channels"`
	TimeoutSeconds int `json:"timeout_seconds"`
	Status HitlStatus `json:"status"`
	Keypair map[string]any `json:"keypair"`
	Environment string `json:"environment"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

// HitlAuthorizationResponse Response from requesting authorization consent for HITL channels
type HitlAuthorizationResponse struct {
	HitlID ObjectId `json:"hitl_id"`
	Authorizations []map[string]any `json:"authorizations"`
	Message string `json:"message"`
}

// HitlFinalizeResponse Finalized HITL configuration (pending → active) with optional authorization dispatch results
type HitlFinalizeResponse struct {
	ID ObjectId `json:"id"`
	UserID *ObjectId `json:"user_id"`
	Name *string `json:"name,omitempty"`
	ProfileID *ObjectId `json:"profile_id,omitempty"`
	CircleID *ObjectId `json:"circle_id,omitempty"`
	Channels []HitlChannel `json:"channels"`
	TimeoutSeconds int `json:"timeout_seconds"`
	Status HitlStatus `json:"status"`
	Keypair map[string]any `json:"keypair"`
	Environment string `json:"environment"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	Authorizations []map[string]any `json:"authorizations,omitempty"`
}

// HitlListResponse Paginated list of HITL configurations
type HitlListResponse struct {
	Data []Hitl `json:"data"`
	Pagination map[string]any `json:"pagination"`
	Limits map[string]any `json:"limits"`
}

// ProfileBadgeResponse Everything needed to embed the verification badge for a username (proof.holdings/badge/{username})
type ProfileBadgeResponse struct {
	Username string `json:"username"`
	Subject string `json:"subject"`
	VerifiedCount int `json:"verified_count"`
	State string `json:"state"`
	CheckedAt string `json:"checked_at"`
	ProfileURL string `json:"profile_url"`
	BadgeUrls map[string]any `json:"badge_urls"`
	Snippets map[string]any `json:"snippets"`
}

// ProfileTemplateContent Body for a profile-scoped template write. Distinct from the account-level `TemplateContent`: it also accepts `is_active`, which every read of the template returns — declaring `TemplateContent` here published a field callers could read and had no documented way to set.
type ProfileTemplateContent struct {
	Subject *string `json:"subject,omitempty"`
	Body string `json:"body"`
	ButtonText *string `json:"button_text,omitempty"`
	ButtonURLTemplate *string `json:"button_url_template,omitempty"`
	IsActive *bool `json:"is_active,omitempty"`
}

// PutHitlKeysBody The client-generated RSA keypair for a HITL config. `public_key`, `encrypted_private_key` and `kdf_salt` are required; the `wrapped_dek`/`dek_iv`/`dek_tag` trio carries the v2 master-key envelope and the `backup_*` trio the recovery wrapper. The server never receives the master password, so it cannot decrypt any of it.
type PutHitlKeysBody struct {
	PublicKey string `json:"public_key"`
	EncryptedPrivateKey string `json:"encrypted_private_key"`
	KdfSalt string `json:"kdf_salt"`
	WrappedDek *string `json:"wrapped_dek,omitempty"`
	DekIv *string `json:"dek_iv,omitempty"`
	DekTag *string `json:"dek_tag,omitempty"`
	BackupWrappedDek *string `json:"backup_wrapped_dek,omitempty"`
	BackupDekIv *string `json:"backup_dek_iv,omitempty"`
	BackupDekTag *string `json:"backup_dek_tag,omitempty"`
}

// RequestHealthHistoryQueryParams Completion-rate history query parameters
type RequestHealthHistoryQueryParams struct {
	Days *int `json:"days,omitempty"`
	Interval *string `json:"interval,omitempty"`
	Environment *string `json:"environment,omitempty"`
}

// RequestHealthHistoryResponse Per-bucket completion-rate trend: requests bucketed by created_at (UTC day/week), reusing /me/summary's stale-expiry bucketing and completed/(completed+expired+cancelled) rate. Dense (zero-filled), chronological. Counts + rate only — no recipient identifiers (SEC-001). Demo traffic excluded (SEC-003).
type RequestHealthHistoryResponse struct {
	Interval string `json:"interval"`
	Days float64 `json:"days"`
	AsOf string `json:"as_of"`
	Points []map[string]any `json:"points"`
}

// ResolveLinkMetadata Approval link metadata returned by GET /resolve. For resolved confirmations, includes history fields.
type ResolveLinkMetadata struct {
	ConfirmationID string `json:"confirmation_id"`
	HitlID string `json:"hitl_id"`
	Status string `json:"status"`
	Encrypted bool `json:"encrypted"`
	TimeoutAt string `json:"timeout_at"`
	CreatedAt string `json:"created_at"`
	ConfigName *string `json:"config_name"`
	ConfigArchived *bool `json:"config_archived,omitempty"`
	BusinessName *string `json:"business_name,omitempty"`
	LogoURL *string `json:"logo_url,omitempty"`
	Response map[string]any `json:"response,omitempty"`
	ResolvedAt *string `json:"resolved_at,omitempty"`
	MaskedActor *string `json:"masked_actor,omitempty"`
}

// SetMasterKeyBody HITL master-key KDF salt to set or change
type SetMasterKeyBody struct {
	MasterKdfSalt string `json:"master_kdf_salt"`
	BackupKdfSalt *string `json:"backup_kdf_salt,omitempty"`
}

type StatusListToken = string

// SummaryQueryParams Account summary query parameters
type SummaryQueryParams struct {
	Environment *string `json:"environment,omitempty"`
	ProfileID *string `json:"profile_id,omitempty"`
}

// SuspendProofResponse Result of a suspend/unsuspend transition (m-proof-status-list)
type SuspendProofResponse struct {
	ProofID string `json:"proof_id"`
	Status string `json:"status"`
	SuspendedAt *string `json:"suspended_at"`
	StatusListUri string `json:"status_list_uri"`
}

// ProfileTemplate A message template as resolved for one public profile — either the profile override or the inherited default.
type ProfileTemplate struct {
	Channel TemplateChannel `json:"channel"`
	MessageType string `json:"message_type"`
	Subject *string `json:"subject,omitempty"`
	Body string `json:"body"`
	ButtonText *string `json:"button_text,omitempty"`
	ButtonURLTemplate *string `json:"button_url_template,omitempty"`
	IsCustom bool `json:"is_custom"`
	IsActive bool `json:"is_active"`
}

// UpdateAuthorizationBody Request body for updating an authorization's owner-editable metadata (F22)
type UpdateAuthorizationBody struct {
	Label *string `json:"label"`
}

// UpdateCircleBody Request body for updating a Circle (name and owner name — the profile binding is create-only)
type UpdateCircleBody struct {
	Name *string `json:"name,omitempty"`
	OwnerName *string `json:"owner_name,omitempty"`
}

// UpdateHitlBody Request body for updating a HITL configuration
type UpdateHitlBody struct {
	Name *string `json:"name,omitempty"`
	Channels []HitlChannel `json:"channels,omitempty"`
	TimeoutSeconds *float64 `json:"timeout_seconds,omitempty"`
}

// MultiChannelChannelBlock Per-channel setup block of a multi-channel verification group
type MultiChannelChannelBlock struct {
	Channel MultiChannelPhoneChannel `json:"channel"`
	VerificationID ObjectId `json:"verification_id"`
	Status VerificationStatus `json:"status"`
	DeepLink *string `json:"deep_link,omitempty"`
	QRCode *string `json:"qr_code,omitempty"`
	QRText *string `json:"qr_text,omitempty"`
	Message *string `json:"message,omitempty"`
	Instructions *string `json:"instructions,omitempty"`
	PhoneNumber *string `json:"phone_number,omitempty"`
	SmsMessage *string `json:"sms_message,omitempty"`
	SmsDids map[string]any `json:"sms_dids,omitempty"`
	SuggestedRegion *string `json:"suggested_region,omitempty"`
}

// MultiChannelGroupStatusResponse Polling status of a multi-channel verification group
type MultiChannelGroupStatusResponse struct {
	GroupID string `json:"group_id"`
	Status string `json:"status"`
	WinningChannel *MultiChannelPhoneChannel `json:"winning_channel"`
	Channels []map[string]any `json:"channels"`
	Proof any `json:"proof,omitempty"`
}

// MultiChannelVerificationResponse Multi-channel verification group with one setup block per channel
type MultiChannelVerificationResponse struct {
	GroupID string `json:"group_id"`
	Type string `json:"type"`
	Identifier string `json:"identifier"`
	Status VerificationStatus `json:"status"`
	ExpiresAt string `json:"expires_at"`
	ExternalUserID *string `json:"external_user_id,omitempty"`
	ClientMetadata map[string]any `json:"client_metadata,omitempty"`
	Channels []MultiChannelChannelBlock `json:"channels"`
	CreatedAt string `json:"created_at"`
}

// ProfileAssetOption An active asset offered for display on a public profile
type ProfileAssetOption struct {
	ID ObjectId `json:"id"`
	Type VerificationType `json:"type"`
	Identifier string `json:"identifier"`
	Channel AssetChannel `json:"channel"`
	VerifiedAt *string `json:"verified_at,omitempty"`
	IsPublic bool `json:"is_public"`
}

// SettingsResponse Account settings
type SettingsResponse struct {
	Branding BrandingSettings `json:"branding"`
	Webhook WebhookSettingsResponse `json:"webhook"`
	ProofExpiryDays *int `json:"proof_expiry_days"`
}

// ============================================================================
// Verification Requests
// ============================================================================

// ActionContext Context for custom and confirmation action types
type ActionContext struct {
	Title *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Amount *float64 `json:"amount,omitempty"`
	Currency *string `json:"currency,omitempty"`
	Entity *string `json:"entity,omitempty"`
}

// ActionType represents the possible values for action type.
type ActionType = string

type CancelRequestResponse struct {
	ID ObjectId `json:"id"`
	Status string `json:"status"`
	Message string `json:"message"`
}

type ReferenceIdParam struct {
	ReferenceID string `json:"referenceId"`
}

// RequestedAsset Asset to be verified in a multi-asset request
type RequestedAsset struct {
	Type VerificationType `json:"type"`
	Identifier *string `json:"identifier,omitempty"`
	Channel *VerificationChannel `json:"channel,omitempty"`
	AllowedChannels []VerificationChannel `json:"allowed_channels,omitempty"`
	Required *bool `json:"required,omitempty"`
}

// ============================================================================
// Domains
// ============================================================================

// AddDomainRequest Request body for adding a domain
type AddDomainRequest struct {
	Domain string `json:"domain"`
	ProfileID *string `json:"profile_id,omitempty"`
	ForEmailSending *bool `json:"for_email_sending,omitempty"`
	VerificationMethod *string `json:"verification_method,omitempty"`
}

// ConnectCloudflareRequest Request body for connecting a Cloudflare API token
type ConnectCloudflareRequest struct {
	APIToken string `json:"api_token"`
}

// ConnectGoDaddyRequest Request body for connecting GoDaddy API credentials
type ConnectGoDaddyRequest struct {
	APIKey string `json:"api_key"`
	APISecret string `json:"api_secret"`
}

// ConnectProviderRequest Request body for connecting a generic DNS provider
type ConnectProviderRequest struct {
	Credentials map[string]any `json:"credentials"`
}

// DomainStatus represents the possible values for domain status.
type DomainStatus = string

// Domain Domain record
type Domain struct {
	ID ObjectId `json:"id"`
	Domain string `json:"domain"`
	Status DomainStatus `json:"status"`
	VerificationMethod *string `json:"verification_method,omitempty"`
	Provider *string `json:"provider,omitempty"`
	EmailSendingEnabled *bool `json:"email_sending_enabled,omitempty"`
	ProfileID *ObjectId `json:"profile_id,omitempty"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	VerifiedAt *string `json:"verified_at,omitempty"`
	ProofID *string `json:"proof_id,omitempty"`
	ProofStatus *string `json:"proof_status,omitempty"`
	ProofRevokedReason *string `json:"proof_revoked_reason,omitempty"`
}

// DomainCheckResponse Domain verification check result
type DomainCheckResponse struct {
	ID ObjectId `json:"id"`
	Domain string `json:"domain"`
	Status string `json:"status"`
	Verified bool `json:"verified"`
	VerifiedAt *string `json:"verified_at"`
	CheckCount int `json:"check_count"`
}

// DomainVerificationResponse Domain verification initiation response
type DomainVerificationResponse struct {
	ID ObjectId `json:"id"`
	Domain string `json:"domain"`
	Status string `json:"status"`
	VerificationMethod string `json:"verification_method"`
	DNSRecord map[string]any `json:"dns_record"`
	HTTPFile map[string]any `json:"http_file"`
	Provider map[string]any `json:"provider"`
}

type ProviderParam struct {
	ID ObjectId `json:"id"`
	Provider string `json:"provider"`
}

// SetupEmailSendingRequest Request body for setting up email sending on a domain
type SetupEmailSendingRequest struct {
	FromEmail *string `json:"from_email,omitempty"`
}

// StartDomainVerificationRequest Request body for starting B2B domain verification
type StartDomainVerificationRequest struct {
	Domain string `json:"domain"`
	CustomerID *string `json:"customer_id,omitempty"`
	VerificationMethod *string `json:"verification_method,omitempty"`
}

// StartEmailVerificationRequest Request body for starting email-based domain verification
type StartEmailVerificationRequest struct {
	EmailPrefix *string `json:"email_prefix,omitempty"`
}

// StartUserDomainVerificationRequest Request body for starting user domain verification
type StartUserDomainVerificationRequest struct {
	Domain string `json:"domain"`
	Channel *string `json:"channel,omitempty"`
}

// ============================================================================
// Emails
// ============================================================================

// AddEmailRequest Request body for adding a new email
type AddEmailRequest struct {
	Email string `json:"email"`
}

// UserEmail User email address
type UserEmail struct {
	ID ObjectId `json:"id"`
	Email string `json:"email"`
	IsPrimary bool `json:"is_primary"`
	VerifiedAt *string `json:"verified_at,omitempty"`
	CreatedAt string `json:"created_at"`
}

// VerifyCodeRequest OTP code submission
type VerifyCodeRequest struct {
	Code string `json:"code"`
}

// ============================================================================
// Phones
// ============================================================================

// AddPhoneRequest Request body for adding a new phone
type AddPhoneRequest struct {
	Channel string `json:"channel"`
}

// UserPhone User phone number
type UserPhone struct {
	ID ObjectId `json:"id"`
	Phone string `json:"phone"`
	IsPrimary bool `json:"is_primary"`
	VerifiedAt *string `json:"verified_at,omitempty"`
	CreatedAt string `json:"created_at"`
	ChannelMetadata map[string]any `json:"channel_metadata,omitempty"`
}

// ============================================================================
// Assets
// ============================================================================

// AssetStatus represents the possible values for asset status.
type AssetStatus = string

// ListAssetsQuery Query parameters for listing assets
type ListAssetsQuery struct {
	Type *string `json:"type,omitempty"`
	Status *AssetStatus `json:"status,omitempty"`
}

type AssetIndexParam struct {
	ID ObjectId `json:"id"`
	AssetIndex string `json:"assetIndex"`
}

// UserAsset User verified asset
type UserAsset struct {
	ID ObjectId `json:"id"`
	Type VerificationType `json:"type"`
	Channel AssetChannel `json:"channel"`
	Identifier string `json:"identifier"`
	Status AssetStatus `json:"status"`
	ProofID *string `json:"proof_id,omitempty"`
	ProofStatus *string `json:"proof_status,omitempty"`
	ProofToken *string `json:"proof_token,omitempty"`
	HasProof *bool `json:"has_proof,omitempty"`
	VerifiedAt *string `json:"verified_at,omitempty"`
	ProofExpiresAt string `json:"proof_expires_at"`
	Metadata map[string]any `json:"metadata,omitempty"`
	CreatedAt string `json:"created_at"`
}

// ============================================================================
// Auth
// ============================================================================

// AuthChannel represents the possible values for auth channel.
type AuthChannel = string

type AuthSessionIdParam struct {
	SessionID string `json:"sessionId"`
}

// AuthSessionListItem Active session entry
type AuthSessionListItem struct {
	ID string `json:"id"`
	Channel AuthChannel `json:"channel"`
	UserAgent *string `json:"user_agent,omitempty"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
	IsCurrent bool `json:"is_current"`
}

// AuthSessionStatus represents the possible values for auth session status.
type AuthSessionStatus = string

// AuthSessionResponse Auth session response
type AuthSessionResponse struct {
	ID string `json:"id"`
	Type string `json:"type"`
	Channel AuthChannel `json:"channel"`
	Status AuthSessionStatus `json:"status"`
	DeepLink *string `json:"deep_link,omitempty"`
	QRCode *string `json:"qr_code,omitempty"`
	QRText *string `json:"qr_text,omitempty"`
	ExpiresAt string `json:"expires_at"`
	Instructions *string `json:"instructions,omitempty"`
	VerifiedAt *string `json:"verified_at,omitempty"`
	UserID *string `json:"user_id,omitempty"`
}

// CreateAuthSessionRequest Request body for creating a new auth session (login)
type CreateAuthSessionRequest struct {
	Channel AuthChannel `json:"channel"`
	PhoneNumber *string `json:"phone_number,omitempty"`
	Email *string `json:"email,omitempty"`
}

// ExchangeTokenRequest Request body for exchanging a one-time token for JWT
type ExchangeTokenRequest struct {
	Token string `json:"token"`
}

// ExchangeTokenResponse Token exchange response
type ExchangeTokenResponse struct {
	Success bool `json:"success"`
	JWT string `json:"jwt"`
	ExpiresAt string `json:"expiresAt"`
}

// ListSessionsResponse List of active sessions
type ListSessionsResponse struct {
	Sessions []AuthSessionListItem `json:"sessions"`
	Total int `json:"total"`
}

// LogoutAllResponse Logout all devices response
type LogoutAllResponse struct {
	Success bool `json:"success"`
	Message string `json:"message"`
	Invalidated int `json:"invalidated"`
}

// AuthUser Authenticated user profile
type AuthUser struct {
	ID ObjectId `json:"id"`
	PhoneNumbers []map[string]any `json:"phone_numbers,omitempty"`
	Emails []map[string]any `json:"emails,omitempty"`
	CreatedAt string `json:"created_at"`
}

// SubmitAuthCodeRequest Request body for submitting an auth OTP code
type SubmitAuthCodeRequest struct {
	Code string `json:"code"`
}

type TokenParam struct {
	Token string `json:"token"`
}

// TransferTokenResponse Transfer token generation response
type TransferTokenResponse struct {
	Success bool `json:"success"`
	Token string `json:"token"`
	URL string `json:"url"`
	ExpiresIn int `json:"expiresIn"`
}

// ============================================================================
// Authorizations
// ============================================================================

// AuthorizationChannel represents the possible values for authorization channel.
type AuthorizationChannel = string

// AuthorizationScope represents the possible values for authorization scope.
type AuthorizationScope = string

// AuthorizationStatus represents the possible values for authorization status.
type AuthorizationStatus = string

type AuthorizationExportQuery struct {
	Format *string `json:"format,omitempty"`
	From *string `json:"from,omitempty"`
	To *string `json:"to,omitempty"`
	Status *AuthorizationStatus `json:"status,omitempty"`
}

type AuthorizationListQuery struct {
	Page *int `json:"page,omitempty"`
	Limit *int `json:"limit,omitempty"`
	Status *AuthorizationStatus `json:"status,omitempty"`
	Phone *string `json:"phone,omitempty"`
	Channel *AuthorizationChannel `json:"channel,omitempty"`
}

// Authorization Authorization granting permission to send confirmations via a specific channel
type Authorization struct {
	ID ObjectId `json:"id"`
	Status AuthorizationStatus `json:"status"`
	HitlID any `json:"hitl_id,omitempty"`
	CircleID any `json:"circle_id,omitempty"`
	Recipient *string `json:"recipient,omitempty"`
	Phone *string `json:"phone,omitempty"`
	Bsuid *string `json:"bsuid,omitempty"`
	Channel AuthorizationChannel `json:"channel"`
	Scope AuthorizationScope `json:"scope"`
	BusinessName string `json:"business_name"`
	Label *string `json:"label,omitempty"`
	RecipientDisplayName *string `json:"recipient_display_name"`
	Enrolled bool `json:"enrolled"`
	VerificationID *ObjectId `json:"verification_id,omitempty"`
	ProofToken *string `json:"proof_token,omitempty"`
	AuthorizedAt *string `json:"authorized_at,omitempty"`
	DeniedAt *string `json:"denied_at,omitempty"`
	ExpiresAt string `json:"expires_at"`
	RevokedAt *string `json:"revoked_at,omitempty"`
	RevocationReason *string `json:"revocation_reason,omitempty"`
	ConfirmationsSent int `json:"confirmations_sent"`
	LastUsedAt *string `json:"last_used_at,omitempty"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type AuthorizationListResponse struct {
	Data []Authorization `json:"data"`
	Pagination map[string]any `json:"pagination"`
}

// AuthorizationWebhookPayload Body of `authorization.approved` / `authorization.denied` — the recipient's answer to a consent request. The recipient's phone/identifier is not included; join on `authorization_id`.
type AuthorizationWebhookPayload struct {
	Event string `json:"event"`
	AuthorizationID ObjectId `json:"authorization_id"`
	HitlID any `json:"hitl_id,omitempty"`
	Status string `json:"status"`
	Channel AuthorizationChannel `json:"channel"`
	Scope *AuthorizationScope `json:"scope,omitempty"`
	ProofToken *string `json:"proof_token,omitempty"`
	DecidedAt *string `json:"decided_at,omitempty"`
	ExpiresAt *string `json:"expires_at,omitempty"`
}

// CreateAuthorizationBody Request body for creating an authorization
type CreateAuthorizationBody struct {
	HitlID any `json:"hitl_id"`
	Recipient string `json:"recipient"`
	Phone string `json:"phone"`
	Bsuid *string `json:"bsuid,omitempty"`
	Channel AuthorizationChannel `json:"channel"`
	Scope *string `json:"scope,omitempty"`
	BusinessName string `json:"business_name"`
	BusinessProfileID any `json:"business_profile_id,omitempty"`
	ExpiresIn *int `json:"expires_in,omitempty"`
}

// CreateAuthorizationResponse Response from creating an authorization request
type CreateAuthorizationResponse struct {
	ID ObjectId `json:"id"`
	Status AuthorizationStatus `json:"status"`
	HitlID any `json:"hitl_id"`
	Recipient *string `json:"recipient,omitempty"`
	Phone *string `json:"phone,omitempty"`
	Bsuid *string `json:"bsuid,omitempty"`
	Channel AuthorizationChannel `json:"channel"`
	Scope AuthorizationScope `json:"scope"`
	BusinessName string `json:"business_name"`
	AuthorizationURL string `json:"authorization_url"`
	ExpiresAt string `json:"expires_at"`
	CreatedAt string `json:"created_at"`
}

type RevokeAuthorizationBody struct {
	Reason *string `json:"reason,omitempty"`
}

// ============================================================================
// Billing
// ============================================================================

// BillingPlan represents the possible values for billing plan.
type BillingPlan = string

// CheckoutRequest Request body for creating a Stripe checkout session
type CheckoutRequest struct {
	Plan BillingPlan `json:"plan"`
	SuccessURL string `json:"success_url"`
	CancelURL string `json:"cancel_url"`
}

// CheckoutResponse Checkout session creation response
type CheckoutResponse struct {
	URL string `json:"url"`
}

// PortalRequest Request body for creating a Stripe billing portal session
type PortalRequest struct {
	ReturnURL string `json:"return_url"`
}

// PortalResponse Billing portal session creation response
type PortalResponse struct {
	URL string `json:"url"`
}

// ============================================================================
// Settings
// ============================================================================

// BrandingSettings Branding settings
type BrandingSettings struct {
	BusinessName *string `json:"business_name,omitempty"`
	LogoURL *string `json:"logo_url,omitempty"`
	PrimaryColor *string `json:"primary_color,omitempty"`
	SupportEmail *string `json:"support_email,omitempty"`
	EmailTheme *string `json:"email_theme,omitempty"`
}

// UsageQueryParams Usage query parameters
type UsageQueryParams struct {
	Period *string `json:"period,omitempty"`
	Months *int `json:"months,omitempty"`
}

// UpdateSettingsRequest Request body for updating user settings
type UpdateSettingsRequest struct {
	Branding *BrandingSettings `json:"branding,omitempty"`
	Webhook *WebhookSettings `json:"webhook,omitempty"`
	ProofExpiryDays *int `json:"proof_expiry_days,omitempty"`
}

// UpdateSettingsResponse Account settings as stored after the update. Carries `webhook.secret` when THIS request created or rotated it — the only response that ever does.
type UpdateSettingsResponse struct {
	Success bool `json:"success"`
	Branding BrandingSettings `json:"branding"`
	Webhook WebhookSettingsResponse `json:"webhook"`
	ProofExpiryDays *int `json:"proof_expiry_days"`
}

// ============================================================================
// Verifications
// ============================================================================

// Challenge Challenge details for verification
type Challenge struct {
	Code *string `json:"code,omitempty"`
	Instruction *string `json:"instruction,omitempty"`
	ExpiresAt *string `json:"expires_at,omitempty"`
}

// DNSProviderCredentials DNS provider credentials for auto-DNS verification
type DNSProviderCredentials struct {
	Provider string `json:"provider"`
	APIToken *string `json:"api_token,omitempty"`
	APIKey *string `json:"api_key,omitempty"`
	APISecret *string `json:"api_secret,omitempty"`
	AccountID *string `json:"account_id,omitempty"`
	Username *string `json:"username,omitempty"`
	AccessKeyID *string `json:"access_key_id,omitempty"`
	SecretAccessKey *string `json:"secret_access_key,omitempty"`
	Region *string `json:"region,omitempty"`
}

// ResendVerificationResponse Response after resending verification email
type ResendVerificationResponse struct {
	Success bool `json:"success"`
	Message string `json:"message"`
	ExpiresAt string `json:"expires_at"`
}

// SubmitChallengeRequest Request body for submitting a challenge code
type SubmitChallengeRequest struct {
	ChallengeCode string `json:"challenge_code"`
	SourceIdentifier *string `json:"source_identifier,omitempty"`
}

// SubmitVerificationCodeRequest Request body for submitting a verification code
type SubmitVerificationCodeRequest struct {
	Code string `json:"code"`
}

// VerificationChannel represents the possible values for verification channel.
type VerificationChannel = string

// VerificationConfidence represents the possible values for verification confidence.
type VerificationConfidence = string

// VerificationRequestListStatus represents the possible values for verification request list status.
type VerificationRequestListStatus = string

type VerificationRequestListQuery struct {
	Page *int `json:"page,omitempty"`
	Limit *int `json:"limit,omitempty"`
	Status *VerificationRequestListStatus `json:"status,omitempty"`
	ReferenceID *string `json:"reference_id,omitempty"`
}

// VerificationRequestStatus represents the possible values for verification request status.
type VerificationRequestStatus = string

// VerificationRequestListItem Verification request as listed: a summary — read the request itself for its assets
type VerificationRequestListItem struct {
	ID ObjectId `json:"id"`
	ReferenceID *string `json:"reference_id,omitempty"`
	Status VerificationRequestStatus `json:"status"`
	ComputedState map[string]any `json:"computed_state"`
	ActionType ActionType `json:"action_type"`
	AssetCount int `json:"asset_count"`
	Progress map[string]any `json:"progress"`
	ExpiresAt string `json:"expires_at"`
	CompletedAt *string `json:"completed_at,omitempty"`
	CreatedAt string `json:"created_at"`
}

type VerificationRequestListResponse struct {
	Data []VerificationRequestListItem `json:"data"`
	Pagination PaginationResponse `json:"pagination"`
}

// VerificationStatus represents the possible values for verification status.
type VerificationStatus = string

// VerificationType represents the possible values for verification type.
type VerificationType = string

// CreateVerificationRequest Request body for creating a new verification
type CreateVerificationRequest struct {
	Type VerificationType `json:"type"`
	Channel VerificationChannel `json:"channel"`
	Identifier string `json:"identifier"`
	ExternalUserID *string `json:"external_user_id,omitempty"`
	ClientMetadata map[string]any `json:"client_metadata,omitempty"`
	DNSProvider any `json:"dns_provider,omitempty"`
	EmailPrefix *string `json:"email_prefix,omitempty"`
	BotToken *string `json:"bot_token,omitempty"`
	ProofExpiryDays *int `json:"proof_expiry_days,omitempty"`
}

// CreateVerificationRequestBody Request body for creating a multi-asset verification request
type CreateVerificationRequestBody struct {
	ReferenceID *string `json:"reference_id,omitempty"`
	PublicProfileID any `json:"public_profile_id,omitempty"`
	Assets []RequestedAsset `json:"assets"`
	ActionType any `json:"action_type,omitempty"`
	ActionContext *ActionContext `json:"action_context,omitempty"`
	ValidityRequirement *string `json:"validity_requirement,omitempty"`
	PartialOk *bool `json:"partial_ok,omitempty"`
	RedirectURL *string `json:"redirect_url,omitempty"`
	CallbackURL *string `json:"callback_url,omitempty"`
	ExpiresIn *int `json:"expires_in,omitempty"`
	ProofExpiryDays *int `json:"proof_expiry_days,omitempty"`
}

type TestVerifyResponse struct {
	ID ObjectId `json:"id"`
	Type VerificationType `json:"type"`
	Channel string `json:"channel"`
	Status string `json:"status"`
	Identifier string `json:"identifier"`
	VerifiedAt string `json:"verified_at"`
	ProofToken string `json:"proof_token"`
	ProofExpiresAt string `json:"proof_expires_at"`
	TestMode bool `json:"test_mode"`
}

// Verification Verification object
type Verification struct {
	ID ObjectId `json:"id"`
	Type VerificationType `json:"type"`
	Channel VerificationChannel `json:"channel"`
	Identifier *string `json:"identifier,omitempty"`
	Status VerificationStatus `json:"status"`
	Challenge *Challenge `json:"challenge,omitempty"`
	Proof *Proof `json:"proof,omitempty"`
	ExternalUserID *string `json:"external_user_id,omitempty"`
	Attempts *int `json:"attempts,omitempty"`
	MaxAttempts *int `json:"max_attempts,omitempty"`
	CreatedAt string `json:"created_at"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	VerifiedAt *string `json:"verified_at,omitempty"`
}

// VerificationListItem Verification as listed
type VerificationListItem struct {
	ID ObjectId `json:"id"`
	Type VerificationType `json:"type"`
	Channel VerificationChannel `json:"channel"`
	Status VerificationStatus `json:"status"`
	Identifier *string `json:"identifier,omitempty"`
	Environment string `json:"environment"`
	CreatedAt string `json:"created_at"`
	VerifiedAt *string `json:"verified_at,omitempty"`
}

type VerificationListQuery struct {
	Page *int `json:"page,omitempty"`
	Limit *int `json:"limit,omitempty"`
	Status *VerificationStatus `json:"status,omitempty"`
	Type *VerificationType `json:"type,omitempty"`
}

// VerificationListResponse Paginated list of verifications
type VerificationListResponse struct {
	Data []VerificationListItem `json:"data"`
	Pagination PaginationResponse `json:"pagination"`
}

// VerificationRequest Multi-asset verification request
type VerificationRequest struct {
	ID ObjectId `json:"id"`
	ReferenceID *string `json:"reference_id,omitempty"`
	Status VerificationRequestStatus `json:"status"`
	ComputedState map[string]any `json:"computed_state,omitempty"`
	Assets []map[string]any `json:"assets"`
	ActionType ActionType `json:"action_type"`
	ActionContext *ActionContext `json:"action_context,omitempty"`
	PartialOk bool `json:"partial_ok"`
	ValidityRequirement *string `json:"validity_requirement,omitempty"`
	VerificationURL *string `json:"verification_url,omitempty"`
	RedirectURL *string `json:"redirect_url,omitempty"`
	CallbackURL *string `json:"callback_url,omitempty"`
	Progress map[string]any `json:"progress,omitempty"`
	ExpiresAt string `json:"expires_at"`
	CompletedAt *string `json:"completed_at,omitempty"`
	CreatedAt string `json:"created_at"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// VerificationRequestProofsResponse Proof tokens for verified assets in a verification request
type VerificationRequestProofsResponse struct {
	Proofs []map[string]any `json:"proofs"`
}

// ============================================================================
// Profiles
// ============================================================================

// ClaimUsernameRequest Request body for claiming a username
type ClaimUsernameRequest struct {
	Username string `json:"username"`
}

// CustomLink Custom link on a public profile
type CustomLink struct {
	Title string `json:"title"`
	URL string `json:"url"`
	Icon *string `json:"icon,omitempty"`
	IsVisible *bool `json:"is_visible,omitempty"`
	DisplayOrder *int `json:"display_order,omitempty"`
}

type ProfileIdParam struct {
	ProfileID string `json:"profileId"`
}

// ProfileProofEntry Proof display configuration for a profile
type ProfileProofEntry struct {
	AssetID string `json:"asset_id"`
	IsVisible *bool `json:"is_visible,omitempty"`
	MaskLevel *string `json:"mask_level,omitempty"`
	DisplayOrder *int `json:"display_order,omitempty"`
	Label *string `json:"label,omitempty"`
}

// ProfileTheme Profile theme customization
type ProfileTheme struct {
	PrimaryColor *string `json:"primary_color,omitempty"`
	BackgroundType *string `json:"background_type,omitempty"`
	BackgroundColor *string `json:"background_color,omitempty"`
	GradientStart *string `json:"gradient_start,omitempty"`
	GradientEnd *string `json:"gradient_end,omitempty"`
	FontStyle *string `json:"font_style,omitempty"`
}

// CreateProfileRequest Request body for creating a new profile
type CreateProfileRequest struct {
	DisplayName *string `json:"display_name,omitempty"`
	Bio *string `json:"bio,omitempty"`
	AvatarURL *string `json:"avatar_url,omitempty"`
	BusinessName *string `json:"business_name,omitempty"`
	IsBusiness *bool `json:"is_business,omitempty"`
	IsPublic *bool `json:"is_public,omitempty"`
	IsPrimary *bool `json:"is_primary,omitempty"`
	Theme *ProfileTheme `json:"theme,omitempty"`
}

// UpdateProfileProofsRequest Request body for updating which proofs are displayed on a profile
type UpdateProfileProofsRequest struct {
	Proofs []ProfileProofEntry `json:"proofs"`
}

// UpdateProfileRequest Request body for updating a profile
type UpdateProfileRequest struct {
	DisplayName *string `json:"display_name,omitempty"`
	Bio *string `json:"bio,omitempty"`
	AvatarURL *string `json:"avatar_url,omitempty"`
	BusinessName *string `json:"business_name,omitempty"`
	IsBusiness *bool `json:"is_business,omitempty"`
	IsPublic *bool `json:"is_public,omitempty"`
	IsPrimary *bool `json:"is_primary,omitempty"`
	ShowVerificationDates *bool `json:"show_verification_dates,omitempty"`
	ShowProofChannels *bool `json:"show_proof_channels,omitempty"`
	Theme *ProfileTheme `json:"theme,omitempty"`
	CustomLinks []CustomLink `json:"custom_links,omitempty"`
}

type UsernameParam struct {
	Username string `json:"username"`
}

// PublicProfile Public profile
type PublicProfile struct {
	ID ObjectId `json:"id"`
	DisplayName *string `json:"display_name,omitempty"`
	Bio *string `json:"bio,omitempty"`
	AvatarURL *string `json:"avatar_url,omitempty"`
	BusinessName *string `json:"business_name,omitempty"`
	IsBusiness *bool `json:"is_business,omitempty"`
	IsPublic bool `json:"is_public"`
	IsPrimary *bool `json:"is_primary,omitempty"`
	Username *string `json:"username,omitempty"`
	Theme *ProfileTheme `json:"theme,omitempty"`
	CustomLinks []CustomLink `json:"custom_links,omitempty"`
	Proofs []map[string]any `json:"proofs,omitempty"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

// ============================================================================
// DNS Credentials
// ============================================================================

// CreateProviderCredentialRequest Request body for creating stored DNS provider credentials
type CreateProviderCredentialRequest struct {
	Provider string `json:"provider"`
	Credentials map[string]any `json:"credentials"`
}

// ============================================================================
// Sessions
// ============================================================================

// CreateSessionRequest Request body for creating a phone verification session
type CreateSessionRequest struct {
	Phone string `json:"phone"`
	Channel *string `json:"channel,omitempty"`
}

// SessionChannel represents the possible values for session channel.
type SessionChannel = string

type SessionIdParam struct {
	ID string `json:"id"`
}

// Session Phone verification session
type Session struct {
	ID ObjectId `json:"id"`
	Status string `json:"status"`
	Challenge *Challenge `json:"challenge,omitempty"`
	Proof *Proof `json:"proof,omitempty"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

// ============================================================================
// Account
// ============================================================================

// DeleteAccountRequest Request body for final account deletion
type DeleteAccountRequest struct {
	SessionID string `json:"session_id"`
}

// InitiateAccountDeletionRequest Request body for initiating account deletion
type InitiateAccountDeletionRequest struct {
	Channel *string `json:"channel,omitempty"`
}

// ============================================================================
// Verified Users
// ============================================================================

type ExternalUserIdParam struct {
	ExternalUserID string `json:"externalUserId"`
}

// VerifiedUserDetail Detailed verification info for a specific external user
type VerifiedUserDetail struct {
	ExternalUserID string `json:"external_user_id"`
	VerificationCount int `json:"verification_count"`
	TypesVerified []VerificationType `json:"types_verified"`
	Verifications []map[string]any `json:"verifications"`
}

// VerifiedUserSummary Aggregated verification summary for an external user
type VerifiedUserSummary struct {
	ExternalUserID string `json:"external_user_id"`
	VerificationCount int `json:"verification_count"`
	TypesVerified []VerificationType `json:"types_verified"`
	Verifications []map[string]any `json:"verifications"`
	FirstVerifiedAt *string `json:"first_verified_at,omitempty"`
	LastVerifiedAt *string `json:"last_verified_at,omitempty"`
}

// VerifiedUserListResponse Paginated list of verified users
type VerifiedUserListResponse struct {
	Data []VerifiedUserSummary `json:"data"`
	Pagination map[string]any `json:"pagination"`
}

// ============================================================================
// Proofs
// ============================================================================

// JWK JSON Web Key. The key-type-specific members are optional because one key set may carry both an EC and an RSA key: `crv`/`x`/`y` are present on EC keys, `n`/`e` on RSA keys.
type JWK struct {
	Kty string `json:"kty"`
	Crv *string `json:"crv,omitempty"`
	X *string `json:"x,omitempty"`
	Y *string `json:"y,omitempty"`
	N *string `json:"n,omitempty"`
	E *string `json:"e,omitempty"`
	Use string `json:"use"`
	Alg string `json:"alg"`
	Kid string `json:"kid"`
}

// JWKS JSON Web Key Set for offline proof verification
type JWKS struct {
	Keys []JWK `json:"keys"`
}

// ProofMePageResponse Public Proof of Me page payload for a username (proof.holdings/me/{username})
type ProofMePageResponse struct {
	Username string `json:"username"`
	DisplayName *string `json:"display_name,omitempty"`
	AvatarURL *string `json:"avatar_url,omitempty"`
	ProofMeEnabled bool `json:"proof_me_enabled"`
	TelegramBotUsername string `json:"telegram_bot_username"`
	WhatsappNumber string `json:"whatsapp_number"`
	TelegramDeepLink string `json:"telegram_deep_link"`
	WhatsappDeepLink string `json:"whatsapp_deep_link"`
	QRCode string `json:"qr_code"`
}

// ProofStatusValue represents the possible values for proof status value.
type ProofStatusValue = string

// ProofStatusResponse Proof status check result
type ProofStatusResponse struct {
	ProofID string `json:"proof_id"`
	Status ProofStatusValue `json:"status"`
	IsValid bool `json:"is_valid"`
	IsRevoked bool `json:"is_revoked"`
	RevokedAt *string `json:"revoked_at"`
	RevokedReason *string `json:"revoked_reason"`
	SuspendedAt *string `json:"suspended_at"`
	ExpiresAt *string `json:"expires_at"`
	IsExpired bool `json:"is_expired"`
}

// ProofTokenChannel represents the possible values for proof token channel.
type ProofTokenChannel = string

// ProofTokenType represents the possible values for proof token type.
type ProofTokenType = string

// RevokeProofRequest Request body for revoking a proof
type RevokeProofRequest struct {
	Reason any `json:"reason,omitempty"`
}

type RevokeProofResponse struct {
	Success bool `json:"success"`
	ProofID *string `json:"proof_id,omitempty"`
	ProofType *string `json:"proof_type,omitempty"`
	VerificationID *string `json:"verification_id,omitempty"`
	RevokedAt string `json:"revoked_at"`
	Reason string `json:"reason"`
}

// RevokedProofType represents the possible values for revoked proof type.
type RevokedProofType = string

// RevokedProof Entry in the revocation list
type RevokedProof struct {
	ProofID *string `json:"proof_id"`
	PublicProofID *string `json:"public_proof_id"`
	ProofType RevokedProofType `json:"proof_type"`
	RevokedAt *string `json:"revoked_at"`
	Reason *RevocationReason `json:"reason"`
}

// RevocationList Signed list of revoked proofs
type RevocationList struct {
	Revoked []RevokedProof `json:"revoked"`
	IssuedAt string `json:"issued_at"`
	Count float64 `json:"count"`
	HasMore bool `json:"has_more"`
	StatusListUri string `json:"status_list_uri"`
	Signature *string `json:"signature"`
	Kid *string `json:"kid"`
}

// ValidateProofRequest Request body for validating a proof token
type ValidateProofRequest struct {
	ProofToken string `json:"proof_token"`
	Identifier *string `json:"identifier,omitempty"`
}

// ValidateProofResponse Proof validation result. Returns verification details when valid, or reason/message when invalid. A DELEGATION token answers with `token_type: "delegation"` and the `delegation` block instead of `verification`; its status resolves the cascade down to the domain control proof, which neither the status list (it packs each row's own bit) nor an offline signature check can show. Delegation-specific reasons: `unknown_delegation` (no registry record — delegations are minted fail-closed, so this is invalid, not merely unresolvable), `status_unavailable`, and `identifier_unverifiable` when an `identifier` binding is requested for a delegation.
type ValidateProofResponse struct {
	Valid bool `json:"valid"`
	ProofID *string `json:"proof_id,omitempty"`
	Verification map[string]any `json:"verification,omitempty"`
	Reason *string `json:"reason,omitempty"`
	SuspendedAt *string `json:"suspended_at,omitempty"`
	Message *string `json:"message,omitempty"`
	RevokedAt *string `json:"revoked_at,omitempty"`
	RevokedReason *string `json:"revoked_reason,omitempty"`
	TokenType *string `json:"token_type,omitempty"`
	Delegation map[string]any `json:"delegation,omitempty"`
}

// Proof Proof token after successful verification
type Proof struct {
	Token string `json:"token"`
	ExpiresAt string `json:"expires_at"`
	Confidence any `json:"confidence,omitempty"`
}

// ============================================================================
// Templates
// ============================================================================

// MessageType represents the possible values for message type.
type MessageType = string

// TemplateChannel represents the possible values for template channel.
type TemplateChannel = string

// Template Message template
type Template struct {
	ID *ObjectId `json:"id,omitempty"`
	ProfileID *ObjectId `json:"profile_id,omitempty"`
	Channel TemplateChannel `json:"channel"`
	MessageType MessageType `json:"message_type"`
	Subject *string `json:"subject,omitempty"`
	Body string `json:"body"`
	ButtonText *string `json:"button_text,omitempty"`
	ButtonURLTemplate *string `json:"button_url_template,omitempty"`
	IsActive *bool `json:"is_active,omitempty"`
	Version *int `json:"version,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// TemplateContent Template content fields
type TemplateContent struct {
	Subject *string `json:"subject,omitempty"`
	Body string `json:"body"`
	ButtonText *string `json:"button_text,omitempty"`
	ButtonURLTemplate *string `json:"button_url_template,omitempty"`
}

type TemplatePathParam struct {
	Channel TemplateChannel `json:"channel"`
	MessageType MessageType `json:"messageType"`
}

// TemplatePreviewRequest Request body for previewing a template
type TemplatePreviewRequest struct {
	Channel TemplateChannel `json:"channel"`
	MessageType MessageType `json:"message_type"`
	Subject *string `json:"subject,omitempty"`
	Body string `json:"body"`
	ButtonText *string `json:"button_text,omitempty"`
	ButtonURLTemplate *string `json:"button_url_template,omitempty"`
}

// TemplateRenderRequest Request body for rendering a template with variables
type TemplateRenderRequest struct {
	Channel TemplateChannel `json:"channel"`
	MessageType MessageType `json:"message_type"`
	Variables map[string]any `json:"variables,omitempty"`
}

type TemplateScopeQuery struct {
	ProfileID any `json:"profile_id,omitempty"`
}

// TemplateVariable Available template variable
type TemplateVariable struct {
	Name string `json:"name"`
	Description string `json:"description"`
}

// ============================================================================
// API Keys
// ============================================================================

// APIKeyResponse API key (key value only shown on creation)
type APIKeyResponse struct {
	ID ObjectId `json:"id"`
	Name string `json:"name"`
	KeyPrefix string `json:"key_prefix"`
	Environment string `json:"environment"`
	Scopes []string `json:"scopes"`
	ProfileID *ObjectId `json:"profile_id,omitempty"`
	CreatedAt string `json:"created_at"`
	LastUsedAt *string `json:"last_used_at,omitempty"`
	ExpiresAt *string `json:"expires_at,omitempty"`
	RevokedAt *string `json:"revoked_at,omitempty"`
}

// CreateAPIKeyRequest Request body for creating an API key
type CreateAPIKeyRequest struct {
	Name *string `json:"name,omitempty"`
	Environment *string `json:"environment,omitempty"`
	Scopes []string `json:"scopes,omitempty"`
	ProfileID any `json:"profile_id,omitempty"`
}

// ============================================================================
// Webhook Deliveries
// ============================================================================

type RetryDeliveryResponse struct {
	Success bool `json:"success"`
	Message string `json:"message"`
	DeliveryID ObjectId `json:"delivery_id"`
	NextRetryAt string `json:"next_retry_at"`
}

// WebhookDeliveryStats Webhook delivery statistics
type WebhookDeliveryStats struct {
	Total int `json:"total"`
	ByStatus map[string]any `json:"by_status"`
	DeliveryRate string `json:"delivery_rate"`
	RecentFailures24h int `json:"recent_failures_24h"`
}

// WebhookDeliveryStatus represents the possible values for webhook delivery status.
type WebhookDeliveryStatus = string

// WebhookEventType represents the possible values for webhook event type.
type WebhookEventType = string

// WebhookDelivery Webhook delivery record
type WebhookDelivery struct {
	ID ObjectId `json:"id"`
	VerificationRequestID *ObjectId `json:"verification_request_id"`
	EventType WebhookEventType `json:"event_type"`
	URL string `json:"url"`
	Status WebhookDeliveryStatus `json:"status"`
	Attempts int `json:"attempts"`
	MaxAttempts int `json:"max_attempts"`
	LastAttemptAt *string `json:"last_attempt_at"`
	NextRetryAt *string `json:"next_retry_at"`
	DeliveredAt *string `json:"delivered_at"`
	ResponseStatus *int `json:"response_status"`
	ErrorMessage *string `json:"error_message"`
	CreatedAt string `json:"created_at"`
	Payload map[string]any `json:"payload"`
	ResponseBody *string `json:"response_body"`
	UpdatedAt string `json:"updated_at"`
}

// WebhookDeliveryListItem Webhook delivery as listed: the payload and the receiver's response body are only on the detail
type WebhookDeliveryListItem struct {
	ID ObjectId `json:"id"`
	VerificationRequestID *ObjectId `json:"verification_request_id"`
	EventType WebhookEventType `json:"event_type"`
	URL string `json:"url"`
	Status WebhookDeliveryStatus `json:"status"`
	Attempts int `json:"attempts"`
	MaxAttempts int `json:"max_attempts"`
	LastAttemptAt *string `json:"last_attempt_at"`
	NextRetryAt *string `json:"next_retry_at"`
	DeliveredAt *string `json:"delivered_at"`
	ResponseStatus *int `json:"response_status"`
	ErrorMessage *string `json:"error_message"`
	CreatedAt string `json:"created_at"`
}

type WebhookDeliveryListQuery struct {
	Page *int `json:"page,omitempty"`
	Limit *int `json:"limit,omitempty"`
	Status *WebhookDeliveryStatus `json:"status,omitempty"`
	EventType *WebhookEventType `json:"event_type,omitempty"`
	VerificationRequestID any `json:"verification_request_id,omitempty"`
}

type WebhookDeliveryListResponse struct {
	Data []WebhookDeliveryListItem `json:"data"`
	Pagination PaginationResponse `json:"pagination"`
}

// WebhookProof Proof of a verified asset included in webhook payload
type WebhookProof struct {
	Type VerificationType `json:"type"`
	Identifier *string `json:"identifier"`
	VerifiedAt *string `json:"verified_at,omitempty"`
	Channel *VerificationChannel `json:"channel"`
	ProofToken *string `json:"proof_token,omitempty"`
	Confidence any `json:"confidence,omitempty"`
}

// WebhookPayload Outbound webhook payload for verification request events (`verification_request.*`), and for `confirmation.approved` when it comes from a verification request created with `action_type: "confirmation"`
type WebhookPayload struct {
	Event WebhookEventType `json:"event"`
	RequestID ObjectId `json:"request_id"`
	ReferenceID *string `json:"reference_id,omitempty"`
	Status VerificationRequestStatus `json:"status"`
	ActionType ActionType `json:"action_type"`
	ActionContext *ActionContext `json:"action_context,omitempty"`
	ClientMetadata map[string]any `json:"client_metadata,omitempty"`
	CompletedAt *string `json:"completed_at,omitempty"`
	Proofs []WebhookProof `json:"proofs"`
	Progress map[string]any `json:"progress"`
	Test *bool `json:"test,omitempty"`
}

// WebhookSettings Outbound webhook configuration. The signing secret is created with the first endpoint; deliveries carry it as an HMAC-SHA256 `X-Proof-Signature` over `<X-Proof-Timestamp>.<body>`.
type WebhookSettings struct {
	URL *string `json:"url,omitempty"`
	Events []string `json:"events,omitempty"`
	RotateSecret *bool `json:"rotate_secret,omitempty"`
}

// WebhookSettingsResponse Outbound webhook configuration as stored.
type WebhookSettingsResponse struct {
	URL *string `json:"url"`
	Events []string `json:"events"`
	SecretSet bool `json:"secret_set"`
	Secret *string `json:"secret,omitempty"`
}

// ============================================================================
// Verify Flow
// ============================================================================

// StartAssetVerificationRequest Request body for starting asset verification in a verification request
type StartAssetVerificationRequest struct {
	Channel string `json:"channel"`
	Identifier *string `json:"identifier,omitempty"`
	BotToken *string `json:"bot_token,omitempty"`
}

// TryItRequest Request body for creating a demo verification request
type TryItRequest struct {
	Type string `json:"type"`
	Identifier string `json:"identifier"`
}

// TryItResponse The 201 of the public demo create. `success` is always true (a failure answers with an error envelope) and `request_id` is the id every subsequent public read takes — `GET /api/v1/verify/request/{id}` and the per-asset status poll. Deliberately NOT the shared `VerificationRequest` component: this path is public, and that component carries the authenticated-owner-only `computed_state` envelope, which must not be advertised here. It names `request_id` rather than `id` — the field the controller has always sent.
type TryItResponse struct {
	Success bool `json:"success"`
	VerificationURL string `json:"verification_url"`
	RequestID ObjectId `json:"request_id"`
	ExpiresAt string `json:"expires_at"`
}

// ============================================================================
// 2FA
// ============================================================================

// TwoFAActionType represents the possible values for two fa action type.
type TwoFAActionType = string

// Start2FARequest Request body for starting 2FA verification
type Start2FARequest struct {
	ActionType TwoFAActionType `json:"action_type"`
	Channel string `json:"channel"`
	EmailID *string `json:"email_id,omitempty"`
	PhoneID *string `json:"phone_id,omitempty"`
	TtlSeconds *int `json:"ttl_seconds,omitempty"`
	SingleUse *bool `json:"single_use,omitempty"`
}

// ============================================================================
// Enum Constants
// ============================================================================

const (
	RevocationReasonUserRequest RevocationReason = "user_request"
	RevocationReasonFraud RevocationReason = "fraud"
	RevocationReasonKeyCompromise RevocationReason = "key_compromise"
	RevocationReasonAssetTransferred RevocationReason = "asset_transferred"
	RevocationReasonOther RevocationReason = "other"
)

const (
	AccountSessionTypeAccountCreation AccountSessionType = "account_creation"
	AccountSessionTypeLogin AccountSessionType = "login"
)

const (
	AssetChannelWhatsapp AssetChannel = "whatsapp"
	AssetChannelTelegram AssetChannel = "telegram"
	AssetChannelSms AssetChannel = "sms"
	AssetChannelEmail AssetChannel = "email"
	AssetChannelDns AssetChannel = "dns"
	AssetChannelHttp AssetChannel = "http"
	AssetChannelAuto AssetChannel = "auto"
	AssetChannelGithub AssetChannel = "github"
	AssetChannelGoogle AssetChannel = "google"
	AssetChannelFacebook AssetChannel = "facebook"
	AssetChannelX AssetChannel = "x"
	AssetChannelLinkedin AssetChannel = "linkedin"
	AssetChannelInstagram AssetChannel = "instagram"
	AssetChannelYoutube AssetChannel = "youtube"
	AssetChannelTiktok AssetChannel = "tiktok"
	AssetChannelEthereum AssetChannel = "ethereum"
	AssetChannelSolana AssetChannel = "solana"
	AssetChannelBitcoin AssetChannel = "bitcoin"
	AssetChannelCoinbase AssetChannel = "coinbase"
	AssetChannelKraken AssetChannel = "kraken"
	AssetChannelTelegramBotToken AssetChannel = "telegram_bot_token"
	AssetChannelOtp AssetChannel = "otp"
	AssetChannelMagicLink AssetChannel = "magic_link"
)

const (
	CircleStatusActive CircleStatus = "active"
	CircleStatusArchived CircleStatus = "archived"
)

const (
	ConfirmationStatusPending ConfirmationStatus = "pending"
	ConfirmationStatusApproved ConfirmationStatus = "approved"
	ConfirmationStatusDenied ConfirmationStatus = "denied"
)

const (
	ConfirmationStatusFilterPending ConfirmationStatusFilter = "pending"
	ConfirmationStatusFilterApproved ConfirmationStatusFilter = "approved"
	ConfirmationStatusFilterDenied ConfirmationStatusFilter = "denied"
	ConfirmationStatusFilterExpired ConfirmationStatusFilter = "expired"
)

const (
	HitlChannelTypeTelegram HitlChannelType = "telegram"
	HitlChannelTypeWhatsapp HitlChannelType = "whatsapp"
	HitlChannelTypeBrowser HitlChannelType = "browser"
)

const (
	HitlStatusPending HitlStatus = "pending"
	HitlStatusActive HitlStatus = "active"
	HitlStatusArchived HitlStatus = "archived"
)

const (
	MultiChannelPhoneChannelWhatsapp MultiChannelPhoneChannel = "whatsapp"
	MultiChannelPhoneChannelTelegram MultiChannelPhoneChannel = "telegram"
	MultiChannelPhoneChannelSms MultiChannelPhoneChannel = "sms"
)

const (
	ActionTypeVerification ActionType = "verification"
	ActionType2fa ActionType = "2fa"
	ActionTypeLogin ActionType = "login"
	ActionTypeCustom ActionType = "custom"
	ActionTypeConfirmation ActionType = "confirmation"
	ActionTypeAuthorization ActionType = "authorization"
)

const (
	DomainStatusPending DomainStatus = "pending"
	DomainStatusVerified DomainStatus = "verified"
	DomainStatusFailed DomainStatus = "failed"
)

const (
	AssetStatusActive AssetStatus = "active"
	AssetStatusExpired AssetStatus = "expired"
	AssetStatusRevoked AssetStatus = "revoked"
)

const (
	AuthChannelTelegram AuthChannel = "telegram"
	AuthChannelWhatsapp AuthChannel = "whatsapp"
	AuthChannelSms AuthChannel = "sms"
	AuthChannelEmail AuthChannel = "email"
)

const (
	AuthSessionStatusPending AuthSessionStatus = "pending"
	AuthSessionStatusVerified AuthSessionStatus = "verified"
	AuthSessionStatusExpired AuthSessionStatus = "expired"
)

const (
	AuthorizationChannelWhatsapp AuthorizationChannel = "whatsapp"
	AuthorizationChannelTelegram AuthorizationChannel = "telegram"
	AuthorizationChannelSms AuthorizationChannel = "sms"
	AuthorizationChannelEmail AuthorizationChannel = "email"
)

const (
	AuthorizationScopeConfirmations AuthorizationScope = "confirmations"
	AuthorizationScopeIdentityChallenge AuthorizationScope = "identity_challenge"
)

const (
	AuthorizationStatusPending AuthorizationStatus = "pending"
	AuthorizationStatusActive AuthorizationStatus = "active"
	AuthorizationStatusExpired AuthorizationStatus = "expired"
	AuthorizationStatusRevoked AuthorizationStatus = "revoked"
	AuthorizationStatusDenied AuthorizationStatus = "denied"
)

const (
	BillingPlanPro BillingPlan = "pro"
	BillingPlanBusiness BillingPlan = "business"
	BillingPlanEnterprise BillingPlan = "enterprise"
)

const (
	VerificationChannelWhatsapp VerificationChannel = "whatsapp"
	VerificationChannelTelegram VerificationChannel = "telegram"
	VerificationChannelSms VerificationChannel = "sms"
	VerificationChannelEmail VerificationChannel = "email"
	VerificationChannelDns VerificationChannel = "dns"
	VerificationChannelHttp VerificationChannel = "http"
	VerificationChannelAuto VerificationChannel = "auto"
	VerificationChannelGithub VerificationChannel = "github"
	VerificationChannelGoogle VerificationChannel = "google"
	VerificationChannelFacebook VerificationChannel = "facebook"
	VerificationChannelX VerificationChannel = "x"
	VerificationChannelLinkedin VerificationChannel = "linkedin"
	VerificationChannelInstagram VerificationChannel = "instagram"
	VerificationChannelYoutube VerificationChannel = "youtube"
	VerificationChannelTiktok VerificationChannel = "tiktok"
	VerificationChannelEthereum VerificationChannel = "ethereum"
	VerificationChannelSolana VerificationChannel = "solana"
	VerificationChannelBitcoin VerificationChannel = "bitcoin"
	VerificationChannelCoinbase VerificationChannel = "coinbase"
	VerificationChannelKraken VerificationChannel = "kraken"
	VerificationChannelTelegramBotToken VerificationChannel = "telegram_bot_token"
)

const (
	VerificationConfidenceHigh VerificationConfidence = "high"
	VerificationConfidenceStandard VerificationConfidence = "standard"
	VerificationConfidenceDegraded VerificationConfidence = "degraded"
)

const (
	VerificationRequestListStatusPending VerificationRequestListStatus = "pending"
	VerificationRequestListStatusPartial VerificationRequestListStatus = "partial"
	VerificationRequestListStatusCompleted VerificationRequestListStatus = "completed"
	VerificationRequestListStatusExpired VerificationRequestListStatus = "expired"
	VerificationRequestListStatusCancelled VerificationRequestListStatus = "cancelled"
	VerificationRequestListStatusActive VerificationRequestListStatus = "active"
)

const (
	VerificationRequestStatusPending VerificationRequestStatus = "pending"
	VerificationRequestStatusPartial VerificationRequestStatus = "partial"
	VerificationRequestStatusCompleted VerificationRequestStatus = "completed"
	VerificationRequestStatusExpired VerificationRequestStatus = "expired"
	VerificationRequestStatusCancelled VerificationRequestStatus = "cancelled"
)

const (
	VerificationStatusPending VerificationStatus = "pending"
	VerificationStatusVerified VerificationStatus = "verified"
	VerificationStatusFailed VerificationStatus = "failed"
	VerificationStatusExpired VerificationStatus = "expired"
	VerificationStatusRevoked VerificationStatus = "revoked"
	VerificationStatusCancelled VerificationStatus = "cancelled"
)

const (
	VerificationTypePhone VerificationType = "phone"
	VerificationTypeEmail VerificationType = "email"
	VerificationTypeDomain VerificationType = "domain"
	VerificationTypeSocial VerificationType = "social"
	VerificationTypeWallet VerificationType = "wallet"
	VerificationTypeAccount VerificationType = "account"
	VerificationTypeTelegramBot VerificationType = "telegram_bot"
)

const (
	SessionChannelTelegram SessionChannel = "telegram"
	SessionChannelWhatsapp SessionChannel = "whatsapp"
	SessionChannelSms SessionChannel = "sms"
)

const (
	ProofStatusValuePending ProofStatusValue = "pending"
	ProofStatusValueActive ProofStatusValue = "active"
	ProofStatusValueFailed ProofStatusValue = "failed"
	ProofStatusValueExpired ProofStatusValue = "expired"
	ProofStatusValueRevoked ProofStatusValue = "revoked"
	ProofStatusValueCancelled ProofStatusValue = "cancelled"
	ProofStatusValueSuspended ProofStatusValue = "suspended"
)

const (
	ProofTokenChannelWhatsapp ProofTokenChannel = "whatsapp"
	ProofTokenChannelTelegram ProofTokenChannel = "telegram"
	ProofTokenChannelSms ProofTokenChannel = "sms"
	ProofTokenChannelEmail ProofTokenChannel = "email"
	ProofTokenChannelDns ProofTokenChannel = "dns"
	ProofTokenChannelHttp ProofTokenChannel = "http"
	ProofTokenChannelAuto ProofTokenChannel = "auto"
	ProofTokenChannelGithub ProofTokenChannel = "github"
	ProofTokenChannelGoogle ProofTokenChannel = "google"
	ProofTokenChannelFacebook ProofTokenChannel = "facebook"
	ProofTokenChannelX ProofTokenChannel = "x"
	ProofTokenChannelLinkedin ProofTokenChannel = "linkedin"
	ProofTokenChannelInstagram ProofTokenChannel = "instagram"
	ProofTokenChannelYoutube ProofTokenChannel = "youtube"
	ProofTokenChannelTiktok ProofTokenChannel = "tiktok"
	ProofTokenChannelEthereum ProofTokenChannel = "ethereum"
	ProofTokenChannelSolana ProofTokenChannel = "solana"
	ProofTokenChannelBitcoin ProofTokenChannel = "bitcoin"
	ProofTokenChannelCoinbase ProofTokenChannel = "coinbase"
	ProofTokenChannelKraken ProofTokenChannel = "kraken"
	ProofTokenChannelTelegramBotToken ProofTokenChannel = "telegram_bot_token"
	ProofTokenChannelBrowser ProofTokenChannel = "browser"
)

const (
	ProofTokenTypePhone ProofTokenType = "phone"
	ProofTokenTypeEmail ProofTokenType = "email"
	ProofTokenTypeDomain ProofTokenType = "domain"
	ProofTokenTypeSocial ProofTokenType = "social"
	ProofTokenTypeWallet ProofTokenType = "wallet"
	ProofTokenTypeAccount ProofTokenType = "account"
	ProofTokenTypeTelegramBot ProofTokenType = "telegram_bot"
	ProofTokenTypeConfirmation ProofTokenType = "confirmation"
	ProofTokenTypeAuthorization ProofTokenType = "authorization"
)

const (
	RevokedProofTypeVerification RevokedProofType = "verification"
	RevokedProofTypeVerificationRequest RevokedProofType = "verification_request"
	RevokedProofTypeConfirmation RevokedProofType = "confirmation"
	RevokedProofTypeAuthorization RevokedProofType = "authorization"
	RevokedProofTypeUserAsset RevokedProofType = "user_asset"
)

const (
	MessageTypeVerificationRequest MessageType = "verification_request"
	MessageTypeVerificationSuccess MessageType = "verification_success"
	MessageTypeVerificationExpired MessageType = "verification_expired"
	MessageTypeLoginRequest MessageType = "login_request"
	MessageTypeLoginSuccess MessageType = "login_success"
	MessageType2faRequest MessageType = "2fa_request"
	MessageType2faSuccess MessageType = "2fa_success"
	MessageTypeAccountDeletionRequest MessageType = "account_deletion_request"
	MessageTypeAccountDeletionSuccess MessageType = "account_deletion_success"
	MessageTypeConfirmationRequest MessageType = "confirmation_request"
	MessageTypeConfirmationApproved MessageType = "confirmation_approved"
	MessageTypeConfirmationDenied MessageType = "confirmation_denied"
)

const (
	TemplateChannelTelegram TemplateChannel = "telegram"
	TemplateChannelWhatsapp TemplateChannel = "whatsapp"
	TemplateChannelSms TemplateChannel = "sms"
	TemplateChannelEmail TemplateChannel = "email"
)

const (
	WebhookDeliveryStatusPending WebhookDeliveryStatus = "pending"
	WebhookDeliveryStatusDelivered WebhookDeliveryStatus = "delivered"
	WebhookDeliveryStatusFailed WebhookDeliveryStatus = "failed"
)

const (
	WebhookEventTypeVerificationRequestCompleted WebhookEventType = "verification_request.completed"
	WebhookEventTypeVerificationRequestPartial WebhookEventType = "verification_request.partial"
	WebhookEventTypeVerificationRequestExpired WebhookEventType = "verification_request.expired"
	WebhookEventTypeVerificationCompleted WebhookEventType = "verification.completed"
	WebhookEventTypeConfirmationApproved WebhookEventType = "confirmation.approved"
	WebhookEventTypeConfirmationDenied WebhookEventType = "confirmation.denied"
	WebhookEventTypeAuthorizationApproved WebhookEventType = "authorization.approved"
	WebhookEventTypeAuthorizationDenied WebhookEventType = "authorization.denied"
	WebhookEventTypeProofRevoked WebhookEventType = "proof.revoked"
	WebhookEventTypeProofSuspended WebhookEventType = "proof.suspended"
	WebhookEventTypeProofUnsuspended WebhookEventType = "proof.unsuspended"
)

const (
	TwoFAActionTypeApiKeyView TwoFAActionType = "api_key_view"
	TwoFAActionTypeApiKeyCreate TwoFAActionType = "api_key_create"
	TwoFAActionTypeApiKeyRevoke TwoFAActionType = "api_key_revoke"
	TwoFAActionTypeApiKeyRegenerate TwoFAActionType = "api_key_regenerate"
	TwoFAActionTypePhoneAdd TwoFAActionType = "phone_add"
	TwoFAActionTypePhoneRemove TwoFAActionType = "phone_remove"
	TwoFAActionTypeEmailAdd TwoFAActionType = "email_add"
	TwoFAActionTypeEmailRemove TwoFAActionType = "email_remove"
	TwoFAActionTypeAccountDelete TwoFAActionType = "account_delete"
	TwoFAActionTypeMasterKeyChange TwoFAActionType = "master_key_change"
	TwoFAActionTypeHitlKeyRotate TwoFAActionType = "hitl_key_rotate"
	TwoFAActionTypeRevocationBulk TwoFAActionType = "revocation_bulk"
	TwoFAActionTypeSettingsWrite TwoFAActionType = "settings_write"
	TwoFAActionTypeProfileUpdate TwoFAActionType = "profile_update"
	TwoFAActionTypeTemplatesWrite TwoFAActionType = "templates_write"
	TwoFAActionTypeWebhookWrite TwoFAActionType = "webhook_write"
	TwoFAActionTypeDelegationLifecycle TwoFAActionType = "delegation_lifecycle"
)
